export {
  MAX_OPTION_DIMENSIONS,
  extractOptionDimensions,
  findVariantByOptions,
  resolveVariantImage,
  buildProductGalleryImages,
  buildStorefrontGallery,
  resolveScrollImageUrl,
  resolveVariantDisplayImage,
  isGeneralImage,
  imageMatchesMediaSelection,
  findGalleryImageIndex,
  isVariantAvailable,
  generateVariantMatrix,
  isOptionValueAvailable,
  hasMultipleVariants,
  getVariantLabel,
  formatVariantLabel,
  countVariantCombinations,
  optionsKey,
  type VariantOptionDimension,
  type VariantLike,
  type ProductImageLike,
} from '@storix/shared';
