/** Auto-generated by scripts/import-debase.ts — do not edit manually. */
/* eslint-disable */

export interface SeedProductImage {
  url: string;
  storageKey: string;
  alt: string;
  sortOrder: number;
}

export interface SeedProductVariant {
  sku: string;
  price: number;
  compareAtPrice?: number;
  inventory: number;
  options: Record<string, string>;
}

export interface SeedProduct {
  name: string;
  slug: string;
  description: string;
  status: 'active';
  metaTitle: string;
  metaDescription: string;
  variants: SeedProductVariant[];
  images: SeedProductImage[];
}

export interface SeedCollection {
  name: string;
  slug: string;
  description: string;
  imageUrl: string;
  productSlugs: string[];
}

export const debaseProducts: SeedProduct[] = [
  {
    "name": "basé SHIRT 04 - Áo Sơ Mi Kẻ Be Logo Thêu Gáy",
    "slug": "base-shirt-04-ao-so-mi-ke-be-logo-theu-gay",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé SHIRT 04 - Áo Sơ Mi Kẻ Be Logo Thêu Gáy | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-SM30042XL",
        "price": 550000,
        "inventory": 15,
        "options": {
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-SM3004M",
        "price": 550000,
        "inventory": 38,
        "options": {
          "size": "M"
        }
      },
      {
        "sku": "DBS-SM3004L",
        "price": 550000,
        "inventory": 36,
        "options": {
          "size": "L"
        }
      },
      {
        "sku": "DBS-SM3004XL",
        "price": 550000,
        "inventory": 15,
        "options": {
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-04-ao-so-mi-ke-be-logo-theu-gay-0.jpg",
        "storageKey": "seed/debase/base-shirt-04-ao-so-mi-ke-be-logo-theu-gay-0.jpg",
        "alt": "basé SHIRT 04 - Áo Sơ Mi Kẻ Be Logo Thêu Gáy",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-04-ao-so-mi-ke-be-logo-theu-gay-1.jpg",
        "storageKey": "seed/debase/base-shirt-04-ao-so-mi-ke-be-logo-theu-gay-1.jpg",
        "alt": "basé SHIRT 04 - Áo Sơ Mi Kẻ Be Logo Thêu Gáy",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-04-ao-so-mi-ke-be-logo-theu-gay-2.jpg",
        "storageKey": "seed/debase/base-shirt-04-ao-so-mi-ke-be-logo-theu-gay-2.jpg",
        "alt": "basé SHIRT 04 - Áo Sơ Mi Kẻ Be Logo Thêu Gáy",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-04-ao-so-mi-ke-be-logo-theu-gay-3.jpg",
        "storageKey": "seed/debase/base-shirt-04-ao-so-mi-ke-be-logo-theu-gay-3.jpg",
        "alt": "basé SHIRT 04 - Áo Sơ Mi Kẻ Be Logo Thêu Gáy",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé SHORT 06 - Quần Cotton dáng A",
    "slug": "base-short-06-quan-cotton-dang-a",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé SHORT 06 - Quần Cotton dáng A | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-QS0144BEIGEL",
        "price": 480000,
        "inventory": 51,
        "options": {
          "color": "BEIGE",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QS0144BEIGEXL",
        "price": 480000,
        "inventory": 44,
        "options": {
          "color": "BEIGE",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QS0144TRANGL",
        "price": 480000,
        "inventory": 34,
        "options": {
          "color": "TRẮNG",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QS0144TRANGXL",
        "price": 480000,
        "inventory": 41,
        "options": {
          "color": "TRẮNG",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QS0144DEN2XL",
        "price": 480000,
        "inventory": 2,
        "options": {
          "color": "ĐEN",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QS0144TRANG2XL",
        "price": 480000,
        "inventory": 6,
        "options": {
          "color": "TRẮNG",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QS0144TRANGM",
        "price": 480000,
        "inventory": 46,
        "options": {
          "color": "TRẮNG",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QS0144DENL",
        "price": 480000,
        "inventory": 33,
        "options": {
          "color": "ĐEN",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QS0144BEIGEM",
        "price": 480000,
        "inventory": 47,
        "options": {
          "color": "BEIGE",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QS0144DENXL",
        "price": 480000,
        "inventory": 28,
        "options": {
          "color": "ĐEN",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QS0144BEIGE2XL",
        "price": 480000,
        "inventory": 4,
        "options": {
          "color": "BEIGE",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QS0144DENM",
        "price": 480000,
        "inventory": 34,
        "options": {
          "color": "ĐEN",
          "size": "M"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-short-06-quan-cotton-dang-a-0.jpg",
        "storageKey": "seed/debase/base-short-06-quan-cotton-dang-a-0.jpg",
        "alt": "basé SHORT 06 - Quần Cotton dáng A",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-short-06-quan-cotton-dang-a-1.jpg",
        "storageKey": "seed/debase/base-short-06-quan-cotton-dang-a-1.jpg",
        "alt": "basé SHORT 06 - Quần Cotton dáng A",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-short-06-quan-cotton-dang-a-2.jpg",
        "storageKey": "seed/debase/base-short-06-quan-cotton-dang-a-2.jpg",
        "alt": "basé SHORT 06 - Quần Cotton dáng A",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-short-06-quan-cotton-dang-a-3.jpg",
        "storageKey": "seed/debase/base-short-06-quan-cotton-dang-a-3.jpg",
        "alt": "basé SHORT 06 - Quần Cotton dáng A",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé SHIRT 02 - Áo Sơ Mi Cotton Thêu Logo Gáy",
    "slug": "base-shirt-02-ao-so-mi-cotton-theu-logo-gay",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé SHIRT 02 - Áo Sơ Mi Cotton Thêu Logo Gáy | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-SM1504XANHPASTELS",
        "price": 580000,
        "inventory": 14,
        "options": {
          "color": "XANH PASTEL",
          "size": "S"
        }
      },
      {
        "sku": "DBS-SM1504TRANG2XL",
        "price": 580000,
        "inventory": 33,
        "options": {
          "color": "TRẮNG",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-SM1504TRANGM",
        "price": 580000,
        "inventory": 51,
        "options": {
          "color": "TRẮNG",
          "size": "M"
        }
      },
      {
        "sku": "DBS-SM1504XANHPASTELL",
        "price": 580000,
        "inventory": 14,
        "options": {
          "color": "XANH PASTEL",
          "size": "L"
        }
      },
      {
        "sku": "DBS-SM1504XANHPASTEL2XL",
        "price": 580000,
        "inventory": 15,
        "options": {
          "color": "XANH PASTEL",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-SM1504XANHCOBANL",
        "price": 580000,
        "inventory": 8,
        "options": {
          "color": "XANH COBAN",
          "size": "L"
        }
      },
      {
        "sku": "DBS-SM1504TRANGL",
        "price": 580000,
        "inventory": 43,
        "options": {
          "color": "TRẮNG",
          "size": "L"
        }
      },
      {
        "sku": "DBS-SM1504TRANGS",
        "price": 580000,
        "inventory": 10,
        "options": {
          "color": "TRẮNG",
          "size": "S"
        }
      },
      {
        "sku": "DBS-SM1504XANHPASTELM",
        "price": 580000,
        "inventory": 15,
        "options": {
          "color": "XANH PASTEL",
          "size": "M"
        }
      },
      {
        "sku": "DBS-SM1504TRANGXL",
        "price": 580000,
        "inventory": 42,
        "options": {
          "color": "TRẮNG",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-SM1504XANHCOBANS",
        "price": 580000,
        "inventory": 19,
        "options": {
          "color": "XANH COBAN",
          "size": "S"
        }
      },
      {
        "sku": "DBS-SM1504XANHCOBANM",
        "price": 580000,
        "inventory": 9,
        "options": {
          "color": "XANH COBAN",
          "size": "M"
        }
      },
      {
        "sku": "DBS-SM1504XANHPASTELXL",
        "price": 580000,
        "inventory": 8,
        "options": {
          "color": "XANH PASTEL",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-SM1504XANHCOBAN2XL",
        "price": 580000,
        "inventory": 12,
        "options": {
          "color": "XANH COBAN",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-SM1504XANHCOBANXL",
        "price": 580000,
        "inventory": 8,
        "options": {
          "color": "XANH COBAN",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-02-ao-so-mi-cotton-theu-logo-gay-0.jpg",
        "storageKey": "seed/debase/base-shirt-02-ao-so-mi-cotton-theu-logo-gay-0.jpg",
        "alt": "basé SHIRT 02 - Áo Sơ Mi Cotton Thêu Logo Gáy",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-02-ao-so-mi-cotton-theu-logo-gay-1.jpg",
        "storageKey": "seed/debase/base-shirt-02-ao-so-mi-cotton-theu-logo-gay-1.jpg",
        "alt": "basé SHIRT 02 - Áo Sơ Mi Cotton Thêu Logo Gáy",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-02-ao-so-mi-cotton-theu-logo-gay-2.jpg",
        "storageKey": "seed/debase/base-shirt-02-ao-so-mi-cotton-theu-logo-gay-2.jpg",
        "alt": "basé SHIRT 02 - Áo Sơ Mi Cotton Thêu Logo Gáy",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-02-ao-so-mi-cotton-theu-logo-gay-3.jpg",
        "storageKey": "seed/debase/base-shirt-02-ao-so-mi-cotton-theu-logo-gay-3.jpg",
        "alt": "basé SHIRT 02 - Áo Sơ Mi Cotton Thêu Logo Gáy",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé POLO 02 - Áo POLO Kẻ Xám Xắn Tay",
    "slug": "base-polo-02-ao-polo-ke-xam-xan-tay",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé POLO 02 - Áo POLO Kẻ Xám Xắn Tay | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-AP1905XL",
        "price": 520000,
        "inventory": 10,
        "options": {
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP19052XL",
        "price": 520000,
        "inventory": 10,
        "options": {
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP1905M",
        "price": 520000,
        "inventory": 20,
        "options": {
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP1905L",
        "price": 520000,
        "inventory": 7,
        "options": {
          "size": "L"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-polo-02-ao-polo-ke-xam-xan-tay-0.jpg",
        "storageKey": "seed/debase/base-polo-02-ao-polo-ke-xam-xan-tay-0.jpg",
        "alt": "basé POLO 02 - Áo POLO Kẻ Xám Xắn Tay",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-polo-02-ao-polo-ke-xam-xan-tay-1.jpg",
        "storageKey": "seed/debase/base-polo-02-ao-polo-ke-xam-xan-tay-1.jpg",
        "alt": "basé POLO 02 - Áo POLO Kẻ Xám Xắn Tay",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-polo-02-ao-polo-ke-xam-xan-tay-2.jpg",
        "storageKey": "seed/debase/base-polo-02-ao-polo-ke-xam-xan-tay-2.jpg",
        "alt": "basé POLO 02 - Áo POLO Kẻ Xám Xắn Tay",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-polo-02-ao-polo-ke-xam-xan-tay-3.jpg",
        "storageKey": "seed/debase/base-polo-02-ao-polo-ke-xam-xan-tay-3.jpg",
        "alt": "basé POLO 02 - Áo POLO Kẻ Xám Xắn Tay",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé PANTS 09 - Quần Kaki Ống Cong 4 Màu",
    "slug": "base-pants-09-quan-kaki-ong-cong-4-mau",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé PANTS 09 - Quần Kaki Ống Cong 4 Màu | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-QD2704XAMCHIXL",
        "price": 850000,
        "inventory": 12,
        "options": {
          "color": "XÁM CHÌ",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QD2704TRANGNGAM",
        "price": 850000,
        "inventory": 10,
        "options": {
          "color": "TRẮNG NGÀ",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QD2704XAMCHIL",
        "price": 850000,
        "inventory": 16,
        "options": {
          "color": "XÁM CHÌ",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QD2704DENXL",
        "price": 850000,
        "inventory": 5,
        "options": {
          "color": "ĐEN",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QD2704XAMCHIM",
        "price": 850000,
        "inventory": 14,
        "options": {
          "color": "XÁM CHÌ",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QD2704TRANGNGAL",
        "price": 850000,
        "inventory": 15,
        "options": {
          "color": "TRẮNG NGÀ",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QD2704TRANGNGA2XL",
        "price": 850000,
        "inventory": 16,
        "options": {
          "color": "TRẮNG NGÀ",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QD2704NAUM",
        "price": 850000,
        "inventory": 30,
        "options": {
          "color": "NÂU",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QD2704DEN2XL",
        "price": 850000,
        "inventory": 18,
        "options": {
          "color": "ĐEN",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QD2704NAUXL",
        "price": 850000,
        "inventory": 28,
        "options": {
          "color": "NÂU",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QD2704NAUL",
        "price": 850000,
        "inventory": 26,
        "options": {
          "color": "NÂU",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QD2704NAU2XL",
        "price": 850000,
        "inventory": 11,
        "options": {
          "color": "NÂU",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QD2704XAMCHI2XL",
        "price": 850000,
        "inventory": 15,
        "options": {
          "color": "XÁM CHÌ",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QD2704DENM",
        "price": 850000,
        "inventory": 13,
        "options": {
          "color": "ĐEN",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QD2704TRANGNGAXL",
        "price": 850000,
        "inventory": 13,
        "options": {
          "color": "TRẮNG NGÀ",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QD2704DENL",
        "price": 850000,
        "inventory": 13,
        "options": {
          "color": "ĐEN",
          "size": "L"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-pants-09-quan-kaki-ong-cong-4-mau-0.jpg",
        "storageKey": "seed/debase/base-pants-09-quan-kaki-ong-cong-4-mau-0.jpg",
        "alt": "basé PANTS 09 - Quần Kaki Ống Cong 4 Màu",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-pants-09-quan-kaki-ong-cong-4-mau-1.jpg",
        "storageKey": "seed/debase/base-pants-09-quan-kaki-ong-cong-4-mau-1.jpg",
        "alt": "basé PANTS 09 - Quần Kaki Ống Cong 4 Màu",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-pants-09-quan-kaki-ong-cong-4-mau-2.jpg",
        "storageKey": "seed/debase/base-pants-09-quan-kaki-ong-cong-4-mau-2.jpg",
        "alt": "basé PANTS 09 - Quần Kaki Ống Cong 4 Màu",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-pants-09-quan-kaki-ong-cong-4-mau-3.jpg",
        "storageKey": "seed/debase/base-pants-09-quan-kaki-ong-cong-4-mau-3.jpg",
        "alt": "basé PANTS 09 - Quần Kaki Ống Cong 4 Màu",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Áo Sơ Mi  - DRAFT SHIRT",
    "slug": "ao-so-mi-draft-shirt",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Áo Sơ Mi  - DRAFT SHIRT | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-SM0407L",
        "price": 490000,
        "inventory": 14,
        "options": {
          "size": "L"
        }
      },
      {
        "sku": "DBS-SM0407M",
        "price": 490000,
        "inventory": 20,
        "options": {
          "size": "M"
        }
      },
      {
        "sku": "DBS-SM04072XL",
        "price": 490000,
        "inventory": 13,
        "options": {
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-SM0407XL",
        "price": 490000,
        "inventory": 33,
        "options": {
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-so-mi-draft-shirt-0.jpg",
        "storageKey": "seed/debase/ao-so-mi-draft-shirt-0.jpg",
        "alt": "Áo Sơ Mi  - DRAFT SHIRT",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-so-mi-draft-shirt-1.jpg",
        "storageKey": "seed/debase/ao-so-mi-draft-shirt-1.jpg",
        "alt": "Áo Sơ Mi  - DRAFT SHIRT",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-so-mi-draft-shirt-2.jpg",
        "storageKey": "seed/debase/ao-so-mi-draft-shirt-2.jpg",
        "alt": "Áo Sơ Mi  - DRAFT SHIRT",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-so-mi-draft-shirt-3.jpg",
        "storageKey": "seed/debase/ao-so-mi-draft-shirt-3.jpg",
        "alt": "Áo Sơ Mi  - DRAFT SHIRT",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Sơ mi Linen Premium - Linen Shirt",
    "slug": "so-mi-linen-premium-linen-shirt",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Sơ mi Linen Premium - Linen Shirt | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-SM0602TRANGS",
        "price": 450000,
        "inventory": 15,
        "options": {
          "color": "Trắng",
          "size": "S"
        }
      },
      {
        "sku": "DBS-SM0602DENS",
        "price": 450000,
        "inventory": 3,
        "options": {
          "color": "Đen",
          "size": "S"
        }
      },
      {
        "sku": "DBS-SM0602TRANGL",
        "price": 450000,
        "inventory": 6,
        "options": {
          "color": "Trắng",
          "size": "L"
        }
      },
      {
        "sku": "DBS-SM0602LATTES",
        "price": 450000,
        "inventory": 8,
        "options": {
          "color": "Latte",
          "size": "S"
        }
      },
      {
        "sku": "DBS-SM0602TRANG2XL",
        "price": 450000,
        "inventory": 2,
        "options": {
          "color": "Trắng",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-SM0602LATTEM",
        "price": 450000,
        "inventory": 14,
        "options": {
          "color": "Latte",
          "size": "M"
        }
      },
      {
        "sku": "DBS-SM0602TRANGXL",
        "price": 450000,
        "inventory": 19,
        "options": {
          "color": "Trắng",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-SM0602LATTEL",
        "price": 450000,
        "inventory": 4,
        "options": {
          "color": "Latte",
          "size": "L"
        }
      },
      {
        "sku": "DBS-SM0602DENXL",
        "price": 450000,
        "inventory": 27,
        "options": {
          "color": "Đen",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-SM0602LATTEXL",
        "price": 450000,
        "inventory": 7,
        "options": {
          "color": "Latte",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-SM0602DENM",
        "price": 450000,
        "inventory": 15,
        "options": {
          "color": "Đen",
          "size": "M"
        }
      },
      {
        "sku": "DBS-SM0602DEN2XL",
        "price": 450000,
        "inventory": 6,
        "options": {
          "color": "Đen",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-SM0602TRANGM",
        "price": 450000,
        "inventory": 7,
        "options": {
          "color": "Trắng",
          "size": "M"
        }
      },
      {
        "sku": "DBS-SM0602LATTE2XL",
        "price": 450000,
        "inventory": 1,
        "options": {
          "color": "Latte",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-SM0602DENL",
        "price": 450000,
        "inventory": 17,
        "options": {
          "color": "Đen",
          "size": "L"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/so-mi-linen-premium-linen-shirt-0.jpg",
        "storageKey": "seed/debase/so-mi-linen-premium-linen-shirt-0.jpg",
        "alt": "Sơ mi Linen Premium - Linen Shirt",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/so-mi-linen-premium-linen-shirt-1.jpg",
        "storageKey": "seed/debase/so-mi-linen-premium-linen-shirt-1.jpg",
        "alt": "Sơ mi Linen Premium - Linen Shirt",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/so-mi-linen-premium-linen-shirt-2.jpg",
        "storageKey": "seed/debase/so-mi-linen-premium-linen-shirt-2.jpg",
        "alt": "Sơ mi Linen Premium - Linen Shirt",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/so-mi-linen-premium-linen-shirt-3.jpg",
        "storageKey": "seed/debase/so-mi-linen-premium-linen-shirt-3.jpg",
        "alt": "Sơ mi Linen Premium - Linen Shirt",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Logo Tee - Áo Phông Logo De Basé",
    "slug": "logo-tee-ao-phong-logo-de-base",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Logo Tee - Áo Phông Logo De Basé | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-AP0306TRANGS",
        "price": 300000,
        "inventory": 15,
        "options": {
          "color": "Trắng",
          "size": "S"
        }
      },
      {
        "sku": "DBS-AP0306NAVYXL",
        "price": 300000,
        "inventory": 12,
        "options": {
          "color": "Navy",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP0306XAM2XL",
        "price": 300000,
        "inventory": 18,
        "options": {
          "color": "Xám",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP0306NAVYS",
        "price": 300000,
        "inventory": 8,
        "options": {
          "color": "Navy",
          "size": "S"
        }
      },
      {
        "sku": "DBS-AP0306XAMS",
        "price": 300000,
        "inventory": 20,
        "options": {
          "color": "Xám",
          "size": "S"
        }
      },
      {
        "sku": "DBS-AP0306XAMM",
        "price": 300000,
        "inventory": 31,
        "options": {
          "color": "Xám",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP0306TRANGL",
        "price": 300000,
        "inventory": 4,
        "options": {
          "color": "Trắng",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP0306XAMXL",
        "price": 300000,
        "inventory": 21,
        "options": {
          "color": "Xám",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP0306XAML",
        "price": 300000,
        "inventory": 22,
        "options": {
          "color": "Xám",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP0306TRANG2XL",
        "price": 300000,
        "inventory": 8,
        "options": {
          "color": "Trắng",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP0306NAVYM",
        "price": 300000,
        "inventory": 20,
        "options": {
          "color": "Navy",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP0306NAVY2XL",
        "price": 300000,
        "inventory": 6,
        "options": {
          "color": "Navy",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP0306TRANGM",
        "price": 300000,
        "inventory": 11,
        "options": {
          "color": "Trắng",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP0306TRANGXL",
        "price": 300000,
        "inventory": 19,
        "options": {
          "color": "Trắng",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP0306NAVYL",
        "price": 300000,
        "inventory": 10,
        "options": {
          "color": "Navy",
          "size": "L"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/logo-tee-ao-phong-logo-de-base-0.jpg",
        "storageKey": "seed/debase/logo-tee-ao-phong-logo-de-base-0.jpg",
        "alt": "Logo Tee - Áo Phông Logo De Basé",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/logo-tee-ao-phong-logo-de-base-1.jpg",
        "storageKey": "seed/debase/logo-tee-ao-phong-logo-de-base-1.jpg",
        "alt": "Logo Tee - Áo Phông Logo De Basé",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/logo-tee-ao-phong-logo-de-base-2.jpg",
        "storageKey": "seed/debase/logo-tee-ao-phong-logo-de-base-2.jpg",
        "alt": "Logo Tee - Áo Phông Logo De Basé",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/logo-tee-ao-phong-logo-de-base-3.jpg",
        "storageKey": "seed/debase/logo-tee-ao-phong-logo-de-base-3.jpg",
        "alt": "Logo Tee - Áo Phông Logo De Basé",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Quần Dạ Ống Rộng - BALLOON Pants",
    "slug": "quan-da-ong-rong-balloon-pants",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Quần Dạ Ống Rộng - BALLOON Pants | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-QXD0810XLNAU",
        "price": 520000,
        "inventory": 10,
        "options": {
          "color": "Nâu",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QXD0810XLKEM",
        "price": 520000,
        "inventory": 12,
        "options": {
          "color": "Kem",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QXD0810LKEM",
        "price": 520000,
        "inventory": 10,
        "options": {
          "color": "Kem",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QXD0810SKEM",
        "price": 520000,
        "inventory": 8,
        "options": {
          "color": "Kem",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QXD0810MKEM",
        "price": 520000,
        "inventory": 20,
        "options": {
          "color": "Kem",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QXD0810SNAU",
        "price": 520000,
        "inventory": 1,
        "options": {
          "color": "Nâu",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QXD0810SDEN",
        "price": 520000,
        "inventory": 15,
        "options": {
          "color": "Đen",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QXD0810LNAU",
        "price": 520000,
        "inventory": 19,
        "options": {
          "color": "Nâu",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QXD0810LDEN",
        "price": 520000,
        "inventory": 25,
        "options": {
          "color": "Đen",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QXD0810MDEN",
        "price": 520000,
        "inventory": 23,
        "options": {
          "color": "Đen",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QXD0810MNAU",
        "price": 520000,
        "inventory": 20,
        "options": {
          "color": "Nâu",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QXD0810XLDEN",
        "price": 520000,
        "inventory": 11,
        "options": {
          "color": "Đen",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/quan-da-ong-rong-balloon-pants-0.jpg",
        "storageKey": "seed/debase/quan-da-ong-rong-balloon-pants-0.jpg",
        "alt": "Quần Dạ Ống Rộng - BALLOON Pants",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/quan-da-ong-rong-balloon-pants-1.jpg",
        "storageKey": "seed/debase/quan-da-ong-rong-balloon-pants-1.jpg",
        "alt": "Quần Dạ Ống Rộng - BALLOON Pants",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/quan-da-ong-rong-balloon-pants-2.jpg",
        "storageKey": "seed/debase/quan-da-ong-rong-balloon-pants-2.jpg",
        "alt": "Quần Dạ Ống Rộng - BALLOON Pants",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/quan-da-ong-rong-balloon-pants-3.jpg",
        "storageKey": "seed/debase/quan-da-ong-rong-balloon-pants-3.jpg",
        "alt": "Quần Dạ Ống Rộng - BALLOON Pants",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "THOMES Wide-leg Pants - Quần Ống Rộng",
    "slug": "thomes-wide-leg-pants-quan-ong-rong",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "THOMES Wide-leg Pants - Quần Ống Rộng | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-QX1006DENS",
        "price": 480000,
        "inventory": 12,
        "options": {
          "color": "ĐEN( Vải Thái)",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QX1006DEN(VAIKAKI)2XL",
        "price": 480000,
        "inventory": 1,
        "options": {
          "color": "ĐEN(Vải Kaki)",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QX1006KAKICREAMXL",
        "price": 480000,
        "inventory": 40,
        "options": {
          "color": "CREAM( Vải Kaki)",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QX1006KAKICREAMS",
        "price": 480000,
        "inventory": 17,
        "options": {
          "color": "CREAM( Vải Kaki)",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QX1006DEN(VAIKAKI)M",
        "price": 480000,
        "inventory": 30,
        "options": {
          "color": "ĐEN(Vải Kaki)",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QX1006KAKICREAML",
        "price": 480000,
        "inventory": 39,
        "options": {
          "color": "CREAM( Vải Kaki)",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QX1006DENXL",
        "price": 480000,
        "inventory": 22,
        "options": {
          "color": "ĐEN( Vải Thái)",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QX1006DEN2XL",
        "price": 480000,
        "inventory": 15,
        "options": {
          "color": "ĐEN( Vải Thái)",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QX1006DEN(VAIKAKI)S",
        "price": 480000,
        "inventory": 34,
        "options": {
          "color": "ĐEN(Vải Kaki)",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QX1006DEN(VAIKAKI)L",
        "price": 480000,
        "inventory": 18,
        "options": {
          "color": "ĐEN(Vải Kaki)",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QX1006DEN(VAIKAKI)XL",
        "price": 480000,
        "inventory": 29,
        "options": {
          "color": "ĐEN(Vải Kaki)",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QX1006DENM",
        "price": 480000,
        "inventory": 11,
        "options": {
          "color": "ĐEN( Vải Thái)",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QX1006DENL",
        "price": 480000,
        "inventory": 39,
        "options": {
          "color": "ĐEN( Vải Thái)",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QX1006KAKICREAM2XL",
        "price": 480000,
        "inventory": 12,
        "options": {
          "color": "CREAM( Vải Kaki)",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QX1006KAKICREAMM",
        "price": 480000,
        "inventory": 19,
        "options": {
          "color": "CREAM( Vải Kaki)",
          "size": "M"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/thomes-wide-leg-pants-quan-ong-rong-0.jpg",
        "storageKey": "seed/debase/thomes-wide-leg-pants-quan-ong-rong-0.jpg",
        "alt": "THOMES Wide-leg Pants - Quần Ống Rộng",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/thomes-wide-leg-pants-quan-ong-rong-1.jpg",
        "storageKey": "seed/debase/thomes-wide-leg-pants-quan-ong-rong-1.jpg",
        "alt": "THOMES Wide-leg Pants - Quần Ống Rộng",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/thomes-wide-leg-pants-quan-ong-rong-2.jpg",
        "storageKey": "seed/debase/thomes-wide-leg-pants-quan-ong-rong-2.jpg",
        "alt": "THOMES Wide-leg Pants - Quần Ống Rộng",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/thomes-wide-leg-pants-quan-ong-rong-3.jpg",
        "storageKey": "seed/debase/thomes-wide-leg-pants-quan-ong-rong-3.jpg",
        "alt": "THOMES Wide-leg Pants - Quần Ống Rộng",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Daddy Pants Ver 2 - Quần Kaki Ống Rộng",
    "slug": "daddy-pants-ver-2-quan-kaki-ong-rong",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Daddy Pants Ver 2 - Quần Kaki Ống Rộng | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-QK2202SDEN",
        "price": 450000,
        "inventory": 15,
        "options": {
          "color": "Đen",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QK2202SKAKI",
        "price": 450000,
        "inventory": 12,
        "options": {
          "color": "Kaki",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QK22022XLKAKI",
        "price": 450000,
        "inventory": 10,
        "options": {
          "color": "Kaki",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QK2202LKAKI",
        "price": 450000,
        "inventory": 3,
        "options": {
          "color": "Kaki",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QK22022XLDEN",
        "price": 450000,
        "inventory": 20,
        "options": {
          "color": "Đen",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-QK2202MDEN",
        "price": 450000,
        "inventory": 17,
        "options": {
          "color": "Đen",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QK2202XLDEN",
        "price": 450000,
        "inventory": 14,
        "options": {
          "color": "Đen",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QK2202LDEN",
        "price": 450000,
        "inventory": 8,
        "options": {
          "color": "Đen",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QK2202MKAKI",
        "price": 450000,
        "inventory": 1,
        "options": {
          "color": "Kaki",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QK2202XLKAKI",
        "price": 450000,
        "inventory": 2,
        "options": {
          "color": "Kaki",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/daddy-pants-ver-2-quan-kaki-ong-rong-0.jpg",
        "storageKey": "seed/debase/daddy-pants-ver-2-quan-kaki-ong-rong-0.jpg",
        "alt": "Daddy Pants Ver 2 - Quần Kaki Ống Rộng",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/daddy-pants-ver-2-quan-kaki-ong-rong-1.jpg",
        "storageKey": "seed/debase/daddy-pants-ver-2-quan-kaki-ong-rong-1.jpg",
        "alt": "Daddy Pants Ver 2 - Quần Kaki Ống Rộng",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/daddy-pants-ver-2-quan-kaki-ong-rong-2.jpg",
        "storageKey": "seed/debase/daddy-pants-ver-2-quan-kaki-ong-rong-2.jpg",
        "alt": "Daddy Pants Ver 2 - Quần Kaki Ống Rộng",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/daddy-pants-ver-2-quan-kaki-ong-rong-3.jpg",
        "storageKey": "seed/debase/daddy-pants-ver-2-quan-kaki-ong-rong-3.jpg",
        "alt": "Daddy Pants Ver 2 - Quần Kaki Ống Rộng",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Daniel Wide-leg Jean - Quần Jean Ống Rộng",
    "slug": "daniel-wide-leg-jean-quan-jean-ong-rong",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Daniel Wide-leg Jean - Quần Jean Ống Rộng | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-QJ0511XLDENIMRAW",
        "price": 500000,
        "inventory": 15,
        "options": {
          "color": "Denim RAW",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QJ0511S",
        "price": 500000,
        "inventory": 12,
        "options": {
          "color": "Denim Wash",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QJ0511LDENIMRAW",
        "price": 500000,
        "inventory": 10,
        "options": {
          "color": "Denim RAW",
          "size": "L"
        }
      },
      {
        "sku": "DBS-QJ0511SDENIMRAW",
        "price": 500000,
        "inventory": 5,
        "options": {
          "color": "Denim RAW",
          "size": "S"
        }
      },
      {
        "sku": "DBS-QJ0511XL",
        "price": 500000,
        "inventory": 14,
        "options": {
          "color": "Denim Wash",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-QJ0511M",
        "price": 500000,
        "inventory": 22,
        "options": {
          "color": "Denim Wash",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QJ0511MDENIMRAW",
        "price": 500000,
        "inventory": 15,
        "options": {
          "color": "Denim RAW",
          "size": "M"
        }
      },
      {
        "sku": "DBS-QJ0511L",
        "price": 500000,
        "inventory": 11,
        "options": {
          "color": "Denim Wash",
          "size": "L"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/daniel-wide-leg-jean-quan-jean-ong-rong-0.jpg",
        "storageKey": "seed/debase/daniel-wide-leg-jean-quan-jean-ong-rong-0.jpg",
        "alt": "Daniel Wide-leg Jean - Quần Jean Ống Rộng",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/daniel-wide-leg-jean-quan-jean-ong-rong-1.jpg",
        "storageKey": "seed/debase/daniel-wide-leg-jean-quan-jean-ong-rong-1.jpg",
        "alt": "Daniel Wide-leg Jean - Quần Jean Ống Rộng",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/daniel-wide-leg-jean-quan-jean-ong-rong-2.jpg",
        "storageKey": "seed/debase/daniel-wide-leg-jean-quan-jean-ong-rong-2.jpg",
        "alt": "Daniel Wide-leg Jean - Quần Jean Ống Rộng",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/daniel-wide-leg-jean-quan-jean-ong-rong-3.jpg",
        "storageKey": "seed/debase/daniel-wide-leg-jean-quan-jean-ong-rong-3.jpg",
        "alt": "Daniel Wide-leg Jean - Quần Jean Ống Rộng",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Áo Khoác Denim - IVAN Cropped Denim Jacket",
    "slug": "ao-khoac-denim-ivan-cropped-denim-jacket",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Áo Khoác Denim - IVAN Cropped Denim Jacket | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-AKB25052XL",
        "price": 680000,
        "inventory": 15,
        "options": {
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AKB2505M",
        "price": 680000,
        "inventory": 11,
        "options": {
          "size": "M"
        }
      },
      {
        "sku": "DBS-AKB2505L",
        "price": 680000,
        "inventory": 10,
        "options": {
          "size": "L"
        }
      },
      {
        "sku": "DBS-AKB2505XL",
        "price": 680000,
        "inventory": 6,
        "options": {
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-khoac-denim-ivan-cropped-denim-jacket-0.jpg",
        "storageKey": "seed/debase/ao-khoac-denim-ivan-cropped-denim-jacket-0.jpg",
        "alt": "Áo Khoác Denim - IVAN Cropped Denim Jacket",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-khoac-denim-ivan-cropped-denim-jacket-1.jpg",
        "storageKey": "seed/debase/ao-khoac-denim-ivan-cropped-denim-jacket-1.jpg",
        "alt": "Áo Khoác Denim - IVAN Cropped Denim Jacket",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-khoac-denim-ivan-cropped-denim-jacket-2.jpg",
        "storageKey": "seed/debase/ao-khoac-denim-ivan-cropped-denim-jacket-2.jpg",
        "alt": "Áo Khoác Denim - IVAN Cropped Denim Jacket",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-khoac-denim-ivan-cropped-denim-jacket-3.jpg",
        "storageKey": "seed/debase/ao-khoac-denim-ivan-cropped-denim-jacket-3.jpg",
        "alt": "Áo Khoác Denim - IVAN Cropped Denim Jacket",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé TRENCH COAT 01 - Áo Khoác Kaki Dài Tay Cong",
    "slug": "base-trench-coat-01-ao-khoac-kaki-dai-tay-cong",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé TRENCH COAT 01 - Áo Khoác Kaki Dài Tay Cong | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-AK0711BEIGEM",
        "price": 1450000,
        "inventory": 3,
        "options": {
          "color": "BEIGE",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AK0711XAMXANHM",
        "price": 1450000,
        "inventory": 2,
        "options": {
          "color": "XÁM XANH",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AK0711BEIGEXL",
        "price": 1450000,
        "inventory": 5,
        "options": {
          "color": "BEIGE",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AK0711XAMXANHXL",
        "price": 1450000,
        "inventory": 10,
        "options": {
          "color": "XÁM XANH",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AK0711XAMXANHL",
        "price": 1450000,
        "inventory": 20,
        "options": {
          "color": "XÁM XANH",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AK0711BEIGEL",
        "price": 1450000,
        "inventory": 12,
        "options": {
          "color": "BEIGE",
          "size": "L"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-trench-coat-01-ao-khoac-kaki-dai-tay-cong-0.jpg",
        "storageKey": "seed/debase/base-trench-coat-01-ao-khoac-kaki-dai-tay-cong-0.jpg",
        "alt": "basé TRENCH COAT 01 - Áo Khoác Kaki Dài Tay Cong",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-trench-coat-01-ao-khoac-kaki-dai-tay-cong-1.jpg",
        "storageKey": "seed/debase/base-trench-coat-01-ao-khoac-kaki-dai-tay-cong-1.jpg",
        "alt": "basé TRENCH COAT 01 - Áo Khoác Kaki Dài Tay Cong",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-trench-coat-01-ao-khoac-kaki-dai-tay-cong-2.jpg",
        "storageKey": "seed/debase/base-trench-coat-01-ao-khoac-kaki-dai-tay-cong-2.jpg",
        "alt": "basé TRENCH COAT 01 - Áo Khoác Kaki Dài Tay Cong",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-trench-coat-01-ao-khoac-kaki-dai-tay-cong-3.jpg",
        "storageKey": "seed/debase/base-trench-coat-01-ao-khoac-kaki-dai-tay-cong-3.jpg",
        "alt": "basé TRENCH COAT 01 - Áo Khoác Kaki Dài Tay Cong",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé PUFFER 03 - Áo Phao Caro",
    "slug": "base-puffer-03-ao-phao-caro",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé PUFFER 03 - Áo Phao Caro | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-AP0301XL",
        "price": 1100000,
        "inventory": 16,
        "options": {
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP03012XL",
        "price": 1100000,
        "inventory": 12,
        "options": {
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP0301L",
        "price": 1100000,
        "inventory": 7,
        "options": {
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP0301M",
        "price": 1100000,
        "inventory": 8,
        "options": {
          "size": "M"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-puffer-03-ao-phao-caro-0.jpg",
        "storageKey": "seed/debase/base-puffer-03-ao-phao-caro-0.jpg",
        "alt": "basé PUFFER 03 - Áo Phao Caro",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-puffer-03-ao-phao-caro-1.jpg",
        "storageKey": "seed/debase/base-puffer-03-ao-phao-caro-1.jpg",
        "alt": "basé PUFFER 03 - Áo Phao Caro",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-puffer-03-ao-phao-caro-2.jpg",
        "storageKey": "seed/debase/base-puffer-03-ao-phao-caro-2.jpg",
        "alt": "basé PUFFER 03 - Áo Phao Caro",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-puffer-03-ao-phao-caro-3.jpg",
        "storageKey": "seed/debase/base-puffer-03-ao-phao-caro-3.jpg",
        "alt": "basé PUFFER 03 - Áo Phao Caro",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Áo Phao - LAZY POCKET PUFFER",
    "slug": "ao-phao-lazy-pocket-puffer",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Áo Phao - LAZY POCKET PUFFER | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-AP1208DENL",
        "price": 860000,
        "inventory": 13,
        "options": {
          "color": "Đen",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP1208DENXL",
        "price": 860000,
        "inventory": 9,
        "options": {
          "color": "Đen",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP1208DENM",
        "price": 860000,
        "inventory": 5,
        "options": {
          "color": "Đen",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP1208CREAM2XL",
        "price": 860000,
        "inventory": 8,
        "options": {
          "color": "Trắng Kem",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP1208DEN2XL",
        "price": 860000,
        "inventory": 20,
        "options": {
          "color": "Đen",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP1208CREAMXL",
        "price": 860000,
        "inventory": 6,
        "options": {
          "color": "Trắng Kem",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP1208CREAML",
        "price": 860000,
        "inventory": 15,
        "options": {
          "color": "Trắng Kem",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP1208CREAMM",
        "price": 860000,
        "inventory": 12,
        "options": {
          "color": "Trắng Kem",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP1208NAUL",
        "price": 860000,
        "inventory": 10,
        "options": {
          "color": "Nâu",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP1208NAUXL",
        "price": 860000,
        "inventory": 8,
        "options": {
          "color": "Nâu",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP1208NAUM",
        "price": 860000,
        "inventory": 20,
        "options": {
          "color": "Nâu",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP1208NAU2XL",
        "price": 860000,
        "inventory": 6,
        "options": {
          "color": "Nâu",
          "size": "2XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-phao-lazy-pocket-puffer-0.jpg",
        "storageKey": "seed/debase/ao-phao-lazy-pocket-puffer-0.jpg",
        "alt": "Áo Phao - LAZY POCKET PUFFER",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-phao-lazy-pocket-puffer-1.jpg",
        "storageKey": "seed/debase/ao-phao-lazy-pocket-puffer-1.jpg",
        "alt": "Áo Phao - LAZY POCKET PUFFER",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-phao-lazy-pocket-puffer-2.jpg",
        "storageKey": "seed/debase/ao-phao-lazy-pocket-puffer-2.jpg",
        "alt": "Áo Phao - LAZY POCKET PUFFER",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-phao-lazy-pocket-puffer-3.jpg",
        "storageKey": "seed/debase/ao-phao-lazy-pocket-puffer-3.jpg",
        "alt": "Áo Phao - LAZY POCKET PUFFER",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé ZIP-UP HOODIE 01 - Áo Khoác Hoodie Zip Nỉ bông 440gsm",
    "slug": "base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé ZIP-UP HOODIE 01 - Áo Khoác Hoodie Zip Nỉ bông 440gsm | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-HD002DENL",
        "price": 1180000,
        "inventory": 3,
        "options": {
          "color": "ĐEN",
          "size": "L"
        }
      },
      {
        "sku": "DBS-HD002DENXL",
        "price": 1180000,
        "inventory": 12,
        "options": {
          "color": "ĐEN",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-HD002XAML",
        "price": 1180000,
        "inventory": 10,
        "options": {
          "color": "XÁM",
          "size": "L"
        }
      },
      {
        "sku": "DBS-HD002XAMM",
        "price": 1180000,
        "inventory": 8,
        "options": {
          "color": "XÁM",
          "size": "M"
        }
      },
      {
        "sku": "DBS-HD002XAMS",
        "price": 1180000,
        "inventory": 25,
        "options": {
          "color": "XÁM",
          "size": "S"
        }
      },
      {
        "sku": "DBS-HD002XAMXL",
        "price": 1180000,
        "inventory": 6,
        "options": {
          "color": "XÁM",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-HD002DENM",
        "price": 1180000,
        "inventory": 9,
        "options": {
          "color": "ĐEN",
          "size": "M"
        }
      },
      {
        "sku": "DBS-HD002DENS",
        "price": 1180000,
        "inventory": 19,
        "options": {
          "color": "ĐEN",
          "size": "S"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm-0.jpg",
        "storageKey": "seed/debase/base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm-0.jpg",
        "alt": "basé ZIP-UP HOODIE 01 - Áo Khoác Hoodie Zip Nỉ bông 440gsm",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm-1.jpg",
        "storageKey": "seed/debase/base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm-1.jpg",
        "alt": "basé ZIP-UP HOODIE 01 - Áo Khoác Hoodie Zip Nỉ bông 440gsm",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm-2.jpg",
        "storageKey": "seed/debase/base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm-2.jpg",
        "alt": "basé ZIP-UP HOODIE 01 - Áo Khoác Hoodie Zip Nỉ bông 440gsm",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm-3.jpg",
        "storageKey": "seed/debase/base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm-3.jpg",
        "alt": "basé ZIP-UP HOODIE 01 - Áo Khoác Hoodie Zip Nỉ bông 440gsm",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Mũ Lưỡi Trai Vành Ngắn - De Cap - De Basé",
    "slug": "mu-luoi-trai-vanh-ngan-de-cap-de-base",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Mũ Lưỡi Trai Vành Ngắn - De Cap - De Basé | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-M0507BENAVY",
        "price": 280000,
        "inventory": 32,
        "options": {
          "color": "BE ( Vành NAVY)"
        }
      },
      {
        "sku": "DBS-M0507BEREU",
        "price": 280000,
        "inventory": 12,
        "options": {
          "color": "BE (Vành Rêu)"
        }
      },
      {
        "sku": "DBS-M0507REUBE",
        "price": 280000,
        "inventory": 8,
        "options": {
          "color": "RÊU (Vành Be)"
        }
      },
      {
        "sku": "DBS-M0507NAVYBE",
        "price": 280000,
        "inventory": 8,
        "options": {
          "color": "NAVY (Vành Be)"
        }
      },
      {
        "sku": "DBS-M0507NAVYTRANG",
        "price": 280000,
        "inventory": 20,
        "options": {
          "color": "NAVY( Chữ Trắng)"
        }
      },
      {
        "sku": "DBS-M0507NAVYCAM",
        "price": 280000,
        "inventory": 68,
        "options": {
          "color": "NAVY (Chữ Cam)"
        }
      },
      {
        "sku": "DBS-M0507DEN",
        "price": 280000,
        "inventory": 21,
        "options": {
          "color": "ĐEN"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/mu-luoi-trai-vanh-ngan-de-cap-de-base-0.jpg",
        "storageKey": "seed/debase/mu-luoi-trai-vanh-ngan-de-cap-de-base-0.jpg",
        "alt": "Mũ Lưỡi Trai Vành Ngắn - De Cap - De Basé",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/mu-luoi-trai-vanh-ngan-de-cap-de-base-1.jpg",
        "storageKey": "seed/debase/mu-luoi-trai-vanh-ngan-de-cap-de-base-1.jpg",
        "alt": "Mũ Lưỡi Trai Vành Ngắn - De Cap - De Basé",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/mu-luoi-trai-vanh-ngan-de-cap-de-base-2.jpg",
        "storageKey": "seed/debase/mu-luoi-trai-vanh-ngan-de-cap-de-base-2.jpg",
        "alt": "Mũ Lưỡi Trai Vành Ngắn - De Cap - De Basé",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/mu-luoi-trai-vanh-ngan-de-cap-de-base-3.jpg",
        "storageKey": "seed/debase/mu-luoi-trai-vanh-ngan-de-cap-de-base-3.jpg",
        "alt": "Mũ Lưỡi Trai Vành Ngắn - De Cap - De Basé",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Cà Vạt - BLANK Caravat",
    "slug": "ca-vat-blank-caravat",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Cà Vạt - BLANK Caravat | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-CV2411",
        "price": 250000,
        "inventory": 15,
        "options": {}
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ca-vat-blank-caravat-0.jpg",
        "storageKey": "seed/debase/ca-vat-blank-caravat-0.jpg",
        "alt": "Cà Vạt - BLANK Caravat",
        "sortOrder": 0
      }
    ]
  },
  {
    "name": "TẤT TRƠN CAO CỔ -  De Basé",
    "slug": "tat-tron-cao-co-de-base",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "TẤT TRƠN CAO CỔ -  De Basé | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-TAT01TRANG",
        "price": 120000,
        "inventory": 66,
        "options": {
          "color": "Trắng"
        }
      },
      {
        "sku": "DBS-TAT01CREAM",
        "price": 120000,
        "inventory": 395,
        "options": {
          "color": "Cream"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/tat-tron-cao-co-de-base-0.jpg",
        "storageKey": "seed/debase/tat-tron-cao-co-de-base-0.jpg",
        "alt": "TẤT TRƠN CAO CỔ -  De Basé",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/tat-tron-cao-co-de-base-1.jpg",
        "storageKey": "seed/debase/tat-tron-cao-co-de-base-1.jpg",
        "alt": "TẤT TRƠN CAO CỔ -  De Basé",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/tat-tron-cao-co-de-base-2.jpg",
        "storageKey": "seed/debase/tat-tron-cao-co-de-base-2.jpg",
        "alt": "TẤT TRƠN CAO CỔ -  De Basé",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/tat-tron-cao-co-de-base-3.jpg",
        "storageKey": "seed/debase/tat-tron-cao-co-de-base-3.jpg",
        "alt": "TẤT TRƠN CAO CỔ -  De Basé",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Túi TOTE Canvas quai Da - De Base Tote",
    "slug": "tui-tote-canvas-quai-da-de-base-tote",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "Túi TOTE Canvas quai Da - De Base Tote | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-TV2603",
        "price": 280000,
        "inventory": 15,
        "options": {}
      },
      {
        "sku": "DBS-TV2603CREAM",
        "price": 280000,
        "inventory": 12,
        "options": {
          "color": "CREAM"
        }
      },
      {
        "sku": "DBS-TV2603DENIM",
        "price": 280000,
        "inventory": 10,
        "options": {
          "color": "DENIM"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/tui-tote-canvas-quai-da-de-base-tote-0.jpg",
        "storageKey": "seed/debase/tui-tote-canvas-quai-da-de-base-tote-0.jpg",
        "alt": "Túi TOTE Canvas quai Da - De Base Tote",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/tui-tote-canvas-quai-da-de-base-tote-1.jpg",
        "storageKey": "seed/debase/tui-tote-canvas-quai-da-de-base-tote-1.jpg",
        "alt": "Túi TOTE Canvas quai Da - De Base Tote",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/tui-tote-canvas-quai-da-de-base-tote-2.jpg",
        "storageKey": "seed/debase/tui-tote-canvas-quai-da-de-base-tote-2.jpg",
        "alt": "Túi TOTE Canvas quai Da - De Base Tote",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/tui-tote-canvas-quai-da-de-base-tote-3.jpg",
        "storageKey": "seed/debase/tui-tote-canvas-quai-da-de-base-tote-3.jpg",
        "alt": "Túi TOTE Canvas quai Da - De Base Tote",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé Logo CAP 01 - Mũ d.",
    "slug": "base-logo-cap-01-mu-d",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé Logo CAP 01 - Mũ d. | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-M0804DAKEXANH",
        "price": 300000,
        "inventory": 15,
        "options": {
          "color": "Dạ Kẻ Xanh"
        }
      },
      {
        "sku": "DBS-M0804DENIMRAW",
        "price": 300000,
        "inventory": 79,
        "options": {
          "color": "Denim RAW"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-logo-cap-01-mu-d-0.jpg",
        "storageKey": "seed/debase/base-logo-cap-01-mu-d-0.jpg",
        "alt": "basé Logo CAP 01 - Mũ d.",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-logo-cap-01-mu-d-1.jpg",
        "storageKey": "seed/debase/base-logo-cap-01-mu-d-1.jpg",
        "alt": "basé Logo CAP 01 - Mũ d.",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-logo-cap-01-mu-d-2.jpg",
        "storageKey": "seed/debase/base-logo-cap-01-mu-d-2.jpg",
        "alt": "basé Logo CAP 01 - Mũ d.",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-logo-cap-01-mu-d-3.jpg",
        "storageKey": "seed/debase/base-logo-cap-01-mu-d-3.jpg",
        "alt": "basé Logo CAP 01 - Mũ d.",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé TEE 02 - Áo Phông Xắn Tay Thêu Logo",
    "slug": "base-tee-02-ao-phong-xan-tay-theu-logo",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé TEE 02 - Áo Phông Xắn Tay Thêu Logo | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-AP1804TRANGXL",
        "price": 420000,
        "inventory": 19,
        "options": {
          "color": "TRẮNG",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP1804DENL",
        "price": 420000,
        "inventory": 12,
        "options": {
          "color": "ĐEN",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP1804TRANGL",
        "price": 420000,
        "inventory": 12,
        "options": {
          "color": "TRẮNG",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP1804DENM",
        "price": 420000,
        "inventory": 2,
        "options": {
          "color": "ĐEN",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP1804XAM2XL",
        "price": 420000,
        "inventory": 22,
        "options": {
          "color": "XÁM",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP1804NAVY2XL",
        "price": 420000,
        "inventory": 6,
        "options": {
          "color": "NAVY",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP1804TRANG2XL",
        "price": 420000,
        "inventory": 1,
        "options": {
          "color": "TRẮNG",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP1804TRANGM",
        "price": 420000,
        "inventory": 21,
        "options": {
          "color": "TRẮNG",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP1804DEN2XL",
        "price": 420000,
        "inventory": 10,
        "options": {
          "color": "ĐEN",
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-AP1804NAVYM",
        "price": 420000,
        "inventory": 19,
        "options": {
          "color": "NAVY",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP1804XAML",
        "price": 420000,
        "inventory": 44,
        "options": {
          "color": "XÁM",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP1804DENXL",
        "price": 420000,
        "inventory": 6,
        "options": {
          "color": "ĐEN",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP1804XAMM",
        "price": 420000,
        "inventory": 46,
        "options": {
          "color": "XÁM",
          "size": "M"
        }
      },
      {
        "sku": "DBS-AP1804NAVYL",
        "price": 420000,
        "inventory": 8,
        "options": {
          "color": "NAVY",
          "size": "L"
        }
      },
      {
        "sku": "DBS-AP1804NAVYXL",
        "price": 420000,
        "inventory": 8,
        "options": {
          "color": "NAVY",
          "size": "XL"
        }
      },
      {
        "sku": "DBS-AP1804XAMXL",
        "price": 420000,
        "inventory": 44,
        "options": {
          "color": "XÁM",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-tee-02-ao-phong-xan-tay-theu-logo-0.jpg",
        "storageKey": "seed/debase/base-tee-02-ao-phong-xan-tay-theu-logo-0.jpg",
        "alt": "basé TEE 02 - Áo Phông Xắn Tay Thêu Logo",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-tee-02-ao-phong-xan-tay-theu-logo-1.jpg",
        "storageKey": "seed/debase/base-tee-02-ao-phong-xan-tay-theu-logo-1.jpg",
        "alt": "basé TEE 02 - Áo Phông Xắn Tay Thêu Logo",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-tee-02-ao-phong-xan-tay-theu-logo-2.jpg",
        "storageKey": "seed/debase/base-tee-02-ao-phong-xan-tay-theu-logo-2.jpg",
        "alt": "basé TEE 02 - Áo Phông Xắn Tay Thêu Logo",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-tee-02-ao-phong-xan-tay-theu-logo-3.jpg",
        "storageKey": "seed/debase/base-tee-02-ao-phong-xan-tay-theu-logo-3.jpg",
        "alt": "basé TEE 02 - Áo Phông Xắn Tay Thêu Logo",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "basé SHIRT 01 - Áo Sơ Mi Cổ Ngược",
    "slug": "base-shirt-01-ao-so-mi-co-nguoc",
    "description": "Details and composition",
    "status": "active",
    "metaTitle": "basé SHIRT 01 - Áo Sơ Mi Cổ Ngược | De Base",
    "metaDescription": "Details and composition",
    "variants": [
      {
        "sku": "DBS-ASM0012XL",
        "price": 620000,
        "inventory": 11,
        "options": {
          "size": "2XL"
        }
      },
      {
        "sku": "DBS-ASM001XL",
        "price": 620000,
        "inventory": 19,
        "options": {
          "size": "XL"
        }
      },
      {
        "sku": "DBS-ASM001M",
        "price": 620000,
        "inventory": 5,
        "options": {
          "size": "M"
        }
      },
      {
        "sku": "DBS-ASM001L",
        "price": 620000,
        "inventory": 32,
        "options": {
          "size": "L"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-01-ao-so-mi-co-nguoc-0.jpg",
        "storageKey": "seed/debase/base-shirt-01-ao-so-mi-co-nguoc-0.jpg",
        "alt": "basé SHIRT 01 - Áo Sơ Mi Cổ Ngược",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-01-ao-so-mi-co-nguoc-1.jpg",
        "storageKey": "seed/debase/base-shirt-01-ao-so-mi-co-nguoc-1.jpg",
        "alt": "basé SHIRT 01 - Áo Sơ Mi Cổ Ngược",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-01-ao-so-mi-co-nguoc-2.jpg",
        "storageKey": "seed/debase/base-shirt-01-ao-so-mi-co-nguoc-2.jpg",
        "alt": "basé SHIRT 01 - Áo Sơ Mi Cổ Ngược",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-01-ao-so-mi-co-nguoc-3.jpg",
        "storageKey": "seed/debase/base-shirt-01-ao-so-mi-co-nguoc-3.jpg",
        "alt": "basé SHIRT 01 - Áo Sơ Mi Cổ Ngược",
        "sortOrder": 3
      }
    ]
  }
];

export const debaseCollections: SeedCollection[] = [
  {
    "name": "New In",
    "slug": "new-in",
    "description": "Latest arrivals from De Base.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-shirt-04-ao-so-mi-ke-be-logo-theu-gay-0.jpg",
    "productSlugs": [
      "base-shirt-04-ao-so-mi-ke-be-logo-theu-gay",
      "base-short-06-quan-cotton-dang-a",
      "base-shirt-02-ao-so-mi-cotton-theu-logo-gay",
      "base-polo-02-ao-polo-ke-xam-xan-tay",
      "base-pants-09-quan-kaki-ong-cong-4-mau"
    ]
  },
  {
    "name": "Tops",
    "slug": "tops",
    "description": "Shirts, tees, and polos from De Base.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-so-mi-draft-shirt-0.jpg",
    "productSlugs": [
      "ao-so-mi-draft-shirt",
      "base-shirt-04-ao-so-mi-ke-be-logo-theu-gay",
      "so-mi-linen-premium-linen-shirt",
      "logo-tee-ao-phong-logo-de-base",
      "base-polo-02-ao-polo-ke-xam-xan-tay"
    ]
  },
  {
    "name": "Bottoms",
    "slug": "bottoms",
    "description": "Pants, jeans, and shorts from De Base.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-short-06-quan-cotton-dang-a-0.jpg",
    "productSlugs": [
      "base-short-06-quan-cotton-dang-a",
      "quan-da-ong-rong-balloon-pants",
      "thomes-wide-leg-pants-quan-ong-rong",
      "daddy-pants-ver-2-quan-kaki-ong-rong",
      "daniel-wide-leg-jean-quan-jean-ong-rong"
    ]
  },
  {
    "name": "Outerwear",
    "slug": "outerwear",
    "description": "Jackets and outer layers from De Base.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/ao-khoac-denim-ivan-cropped-denim-jacket-0.jpg",
    "productSlugs": [
      "ao-khoac-denim-ivan-cropped-denim-jacket",
      "base-trench-coat-01-ao-khoac-kaki-dai-tay-cong",
      "base-puffer-03-ao-phao-caro",
      "ao-phao-lazy-pocket-puffer",
      "base-zip-up-hoodie-01-ao-khoac-hoodie-zip-ni-bong-440gsm"
    ]
  },
  {
    "name": "Accessories",
    "slug": "accessories",
    "description": "Accessories and finishing touches from De Base.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/mu-luoi-trai-vanh-ngan-de-cap-de-base-0.jpg",
    "productSlugs": [
      "mu-luoi-trai-vanh-ngan-de-cap-de-base",
      "ca-vat-blank-caravat",
      "tat-tron-cao-co-de-base",
      "tui-tote-canvas-quai-da-de-base-tote",
      "base-logo-cap-01-mu-d"
    ]
  },
  {
    "name": "Best Sellers",
    "slug": "best-sellers",
    "description": "Top picks from the De Base catalog.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/debase/base-polo-02-ao-polo-ke-xam-xan-tay-0.jpg",
    "productSlugs": [
      "base-polo-02-ao-polo-ke-xam-xan-tay",
      "base-pants-09-quan-kaki-ong-cong-4-mau",
      "base-tee-02-ao-phong-xan-tay-theu-logo",
      "base-shirt-01-ao-so-mi-co-nguoc",
      "so-mi-linen-premium-linen-shirt"
    ]
  }
];
