/** Auto-generated by scripts/import-whose-studio.ts — do not edit manually. */
/* eslint-disable */

export interface SeedProductImage {
  url: string;
  storageKey: string;
  alt: string;
  sortOrder: number;
}

export interface SeedProductVariant {
  sku: string;
  price: number;
  compareAtPrice?: number;
  inventory: number;
  options: Record<string, string>;
}

export interface SeedProduct {
  name: string;
  slug: string;
  description: string;
  status: 'active';
  metaTitle: string;
  metaDescription: string;
  variants: SeedProductVariant[];
  images: SeedProductImage[];
}

export interface SeedCollection {
  name: string;
  slug: string;
  description: string;
  imageUrl: string;
  productSlugs: string[];
}

export const whoseStudioProducts: SeedProduct[] = [
  {
    "name": "BlinkStar Tshirt / Black",
    "slug": "blinkstar-tshirt-black",
    "description": "Chiếc T-shirt được phát triển trên chất liệu cotton 2 chiều 260GSM, dày dặn – mịn mặt – đứng form, cho cảm giác chắc chắn khi mặc nhưng vẫn thoải mái suốt ngày dài. Form big boxy đặc trưng của Whose với thân rộng, rơi tự nhiên, tạo tỷ lệ dáng đẹp và che khuyết điểm hiệu quả.\nĐiểm nhấn nổi bật nằm ở graphic WHISER – Think Positive được xử lý theo phong cách vintage distressed print: mảng chữ được tạo hiệu ứng xước – mờ – phai nhẹ, mang vibe grunge và street hơn, nổi bật trên nền đen nhưng không quá gắt.\nPhần cổ rib giữ form tốt, bo ôm nhẹ; đường may chắc chắn giúp áo bền và hạn chế bai giãn sau nhiều lần giặt.\nĐẶC ĐIỂM NỔI BẬTCotton 250GSM: dày vừa, thoáng, mịn, giữ phom tốt.\nForm big boxy: rộng – thoải mái – rơi tự nhiên.\nVintage distressed print: graphic hiệu ứng xước – phai đặc trưng, mang vibe high-street.\nCổ rib bền, chắc, hạn chế bai.\nDễ phối: hợp denim, quần suông, jogger, layering cùng hoodie/jacket.",
    "status": "active",
    "metaTitle": "BlinkStar Tshirt / Black | Whose Studio",
    "metaDescription": "Chiếc T-shirt được phát triển trên chất liệu cotton 2 chiều 260GSM, dày dặn – mịn mặt – đứng form, cho cảm giác chắc chắn khi mặc nhưng vẫn thoải mái suốt ngày ",
    "variants": [
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-BLA-SP007991",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Đen",
          "size": "S"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-BLA-SP007996",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Đen",
          "size": "M"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-BLA-SP008001",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Đen",
          "size": "L"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-BLA-SP008006",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Đen",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-black-0.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-black-0.jpg",
        "alt": "Đen",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-black-1.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-black-1.jpg",
        "alt": "Đen",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-black-2.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-black-2.jpg",
        "alt": "Đen",
        "sortOrder": 2
      }
    ]
  },
  {
    "name": "BlinkStar Tshirt / Red",
    "slug": "blinkstar-tshirt-red",
    "description": "Chiếc T-shirt được phát triển trên chất liệu cotton 2 chiều 260GSM, dày dặn – mịn mặt – đứng form, cho cảm giác chắc chắn khi mặc nhưng vẫn thoải mái suốt ngày dài. Form big boxy đặc trưng của Whose với thân rộng, rơi tự nhiên, tạo tỷ lệ dáng đẹp và che khuyết điểm hiệu quả.\nĐiểm nhấn nổi bật nằm ở graphic WHISER – Think Positive được xử lý theo phong cách vintage distressed print: mảng chữ được tạo hiệu ứng xước – mờ – phai nhẹ, mang vibe grunge và street hơn, nổi bật trên nền đen nhưng không quá gắt.\nPhần cổ rib giữ form tốt, bo ôm nhẹ; đường may chắc chắn giúp áo bền và hạn chế bai giãn sau nhiều lần giặt.\nĐẶC ĐIỂM NỔI BẬTCotton 250GSM: dày vừa, thoáng, mịn, giữ phom tốt.\nForm big boxy: rộng – thoải mái – rơi tự nhiên.\nVintage distressed print: graphic hiệu ứng xước – phai đặc trưng, mang vibe high-street.\nCổ rib bền, chắc, hạn chế bai.\nDễ phối: hợp denim, quần suông, jogger, layering cùng hoodie/jacket.",
    "status": "active",
    "metaTitle": "BlinkStar Tshirt / Red | Whose Studio",
    "metaDescription": "Chiếc T-shirt được phát triển trên chất liệu cotton 2 chiều 260GSM, dày dặn – mịn mặt – đứng form, cho cảm giác chắc chắn khi mặc nhưng vẫn thoải mái suốt ngày ",
    "variants": [
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-RED-SP007991",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Đỏ",
          "size": "S"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-RED-SP007996",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Đỏ",
          "size": "M"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-RED-SP008001",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Đỏ",
          "size": "L"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-RED-SP008006",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Đỏ",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-red-0.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-red-0.jpg",
        "alt": "Đỏ",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-red-1.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-red-1.jpg",
        "alt": "Đỏ",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-red-2.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-red-2.jpg",
        "alt": "Đỏ",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-red-3.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-red-3.jpg",
        "alt": "Đỏ",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "BlinkStar Tshirt / Tiêu đậm",
    "slug": "blinkstar-tshirt-tieu-dam",
    "description": "Chiếc T-shirt được phát triển trên chất liệu cotton 2 chiều 260GSM, dày dặn – mịn mặt – đứng form, cho cảm giác chắc chắn khi mặc nhưng vẫn thoải mái suốt ngày dài. Form big boxy đặc trưng của Whose với thân rộng, rơi tự nhiên, tạo tỷ lệ dáng đẹp và che khuyết điểm hiệu quả.\nĐiểm nhấn nổi bật nằm ở graphic WHISER – Think Positive được xử lý theo phong cách vintage distressed print: mảng chữ được tạo hiệu ứng xước – mờ – phai nhẹ, mang vibe grunge và street hơn, nổi bật trên nền đen nhưng không quá gắt.\nPhần cổ rib giữ form tốt, bo ôm nhẹ; đường may chắc chắn giúp áo bền và hạn chế bai giãn sau nhiều lần giặt.\nĐẶC ĐIỂM NỔI BẬTCotton 250GSM: dày vừa, thoáng, mịn, giữ phom tốt.\nForm big boxy: rộng – thoải mái – rơi tự nhiên.\nVintage distressed print: graphic hiệu ứng xước – phai đặc trưng, mang vibe high-street.\nCổ rib bền, chắc, hạn chế bai.\nDễ phối: hợp denim, quần suông, jogger, layering cùng hoodie/jacket.",
    "status": "active",
    "metaTitle": "BlinkStar Tshirt / Tiêu đậm | Whose Studio",
    "metaDescription": "Chiếc T-shirt được phát triển trên chất liệu cotton 2 chiều 260GSM, dày dặn – mịn mặt – đứng form, cho cảm giác chắc chắn khi mặc nhưng vẫn thoải mái suốt ngày ",
    "variants": [
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-TIE-SP007991",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Tiêu đậm",
          "size": "S"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-TIE-SP007996",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Tiêu đậm",
          "size": "M"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-TIE-SP008001",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Tiêu đậm",
          "size": "L"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-TIE-SP008006",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Tiêu đậm",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-tieu-dam-0.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-tieu-dam-0.jpg",
        "alt": "Tiêu đậm",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-tieu-dam-1.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-tieu-dam-1.jpg",
        "alt": "Tiêu đậm",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-tieu-dam-2.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-tieu-dam-2.jpg",
        "alt": "Tiêu đậm",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-tieu-dam-3.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-tieu-dam-3.jpg",
        "alt": "Tiêu đậm",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "BlinkStar Tshirt / White",
    "slug": "blinkstar-tshirt-white",
    "description": "Chiếc T-shirt được phát triển trên chất liệu cotton 2 chiều 260GSM, dày dặn – mịn mặt – đứng form, cho cảm giác chắc chắn khi mặc nhưng vẫn thoải mái suốt ngày dài. Form big boxy đặc trưng của Whose với thân rộng, rơi tự nhiên, tạo tỷ lệ dáng đẹp và che khuyết điểm hiệu quả.\nĐiểm nhấn nổi bật nằm ở graphic WHISER – Think Positive được xử lý theo phong cách vintage distressed print: mảng chữ được tạo hiệu ứng xước – mờ – phai nhẹ, mang vibe grunge và street hơn, nổi bật trên nền đen nhưng không quá gắt.\nPhần cổ rib giữ form tốt, bo ôm nhẹ; đường may chắc chắn giúp áo bền và hạn chế bai giãn sau nhiều lần giặt.\nĐẶC ĐIỂM NỔI BẬTCotton 250GSM: dày vừa, thoáng, mịn, giữ phom tốt.\nForm big boxy: rộng – thoải mái – rơi tự nhiên.\nVintage distressed print: graphic hiệu ứng xước – phai đặc trưng, mang vibe high-street.\nCổ rib bền, chắc, hạn chế bai.\nDễ phối: hợp denim, quần suông, jogger, layering cùng hoodie/jacket.",
    "status": "active",
    "metaTitle": "BlinkStar Tshirt / White | Whose Studio",
    "metaDescription": "Chiếc T-shirt được phát triển trên chất liệu cotton 2 chiều 260GSM, dày dặn – mịn mặt – đứng form, cho cảm giác chắc chắn khi mặc nhưng vẫn thoải mái suốt ngày ",
    "variants": [
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-WHI-SP007991",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Trắng",
          "size": "S"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-WHI-SP007996",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Trắng",
          "size": "M"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-WHI-SP008001",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Trắng",
          "size": "L"
        }
      },
      {
        "sku": "WHS-BLINKSTAR-TSHIRT-WHI-SP008006",
        "price": 240000,
        "inventory": 0,
        "options": {
          "color": "Trắng",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-white-0.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-white-0.jpg",
        "alt": "Trắng",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-white-1.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-white-1.jpg",
        "alt": "Trắng",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-white-2.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-white-2.jpg",
        "alt": "Trắng",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-white-3.jpg",
        "storageKey": "seed/products/blinkstar-tshirt-white-3.jpg",
        "alt": "Trắng",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "BODYFIT TEE",
    "slug": "bodyfit-tee",
    "description": "Áo Thun from Whose Studio. Premium streetwear for everyday wear.",
    "status": "active",
    "metaTitle": "BODYFIT TEE | Whose Studio",
    "metaDescription": "Áo Thun from Whose Studio. Premium streetwear for everyday wear.",
    "variants": [
      {
        "sku": "WHS-BODYFIT-TEE-SP009487",
        "price": 180000,
        "inventory": 0,
        "options": {
          "color": "Đen",
          "size": "M"
        }
      },
      {
        "sku": "WHS-BODYFIT-TEE-SP009488",
        "price": 180000,
        "inventory": 0,
        "options": {
          "color": "Xám tiêu đậm",
          "size": "M"
        }
      },
      {
        "sku": "WHS-BODYFIT-TEE-SP009489",
        "price": 180000,
        "inventory": 5,
        "options": {
          "color": "TRẮNG",
          "size": "M"
        }
      },
      {
        "sku": "WHS-BODYFIT-TEE-SP009490",
        "price": 180000,
        "inventory": 1,
        "options": {
          "color": "Đen",
          "size": "L"
        }
      },
      {
        "sku": "WHS-BODYFIT-TEE-SP009491",
        "price": 180000,
        "inventory": 2,
        "options": {
          "color": "Xám tiêu đậm",
          "size": "L"
        }
      },
      {
        "sku": "WHS-BODYFIT-TEE-SP009492",
        "price": 180000,
        "inventory": 2,
        "options": {
          "color": "TRẮNG",
          "size": "L"
        }
      },
      {
        "sku": "WHS-BODYFIT-TEE-SP009493",
        "price": 180000,
        "inventory": 0,
        "options": {
          "color": "Đen",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-BODYFIT-TEE-SP009494",
        "price": 180000,
        "inventory": 8,
        "options": {
          "color": "Xám tiêu đậm",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-BODYFIT-TEE-SP009495",
        "price": 180000,
        "inventory": 2,
        "options": {
          "color": "TRẮNG",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/bodyfit-tee-0.jpg",
        "storageKey": "seed/products/bodyfit-tee-0.jpg",
        "alt": "BODYFIT TEE",
        "sortOrder": 0
      }
    ]
  },
  {
    "name": "507 HDZ SYMBOL",
    "slug": "507-hdz-symbol",
    "description": "Chiếc hoodie được phát triển từ chất liệu nỉ bông PE 350GSM, mang lại cảm giác dày dặn, giữ ấm tốt nhưng vẫn mềm mịn khi chạm vào. Chất liệu PE giúp áo bền form, hạn chế nhăn , phù hợp mặc hằng ngày mà không lo xuống phom hay nặng người.\nPhom relaxed với vai rớt nhẹ, bo gấu – bo tay ôm vừa, giúp tổng thể trông gọn và cân đối. Khóa kéo kim loại hai chiều chắc chắn, thao tác mượt, tạo cảm giác cao cấp. Logo kim loại WHOOSE ở ngực là chi tiết nhấn tinh tế, giữ sự tối giản đặc trưng của thiết kế.\nHoodie còn được trang bị 2 túi trong ẩn, tăng tính tiện dụng và bảo mật, hỗ trợ người dùng khi di chuyển.\nĐặc điểm nổi bậtChất liệu nỉ bông PE 350GSM: dày – ấm – đứng form, bền, ít nhăn.\nForm relaxed fit: thoải mái, hợp nhiều vóc dáng.\nLogo kim loại WHOOSE: sắc sảo, tinh tế, tạo điểm nhấn nhận diện.\nKhóa kéo hai chiều kim loại: chắc chắn, trượt mượt.\n2 túi trong + túi ngoài lớn: tiện dụng, tối ưu không gian chứa đồ.\nBo gấu – bo tay ôm vừa, giữ phom đẹp khi mặc.\nPhong cách gợi ýPhối cùng quần jeans, kaki, wide pants hoặc jogger.\nLayer với tee basic, sơ mi, hoặc khoác ngoài áo khoác nhẹ.\nPhù hợp đi học – đi làm – đi chơi hằng ngày.",
    "status": "active",
    "metaTitle": "507 HDZ SYMBOL | Whose Studio",
    "metaDescription": "Chiếc hoodie được phát triển từ chất liệu nỉ bông PE 350GSM, mang lại cảm giác dày dặn, giữ ấm tốt nhưng vẫn mềm mịn khi chạm vào. Chất liệu PE giúp áo bền form",
    "variants": [
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008891",
        "price": 250000,
        "inventory": 0,
        "options": {
          "color": "Navy",
          "size": "M"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008892",
        "price": 250000,
        "inventory": 22,
        "options": {
          "color": "Navy",
          "size": "L"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008893",
        "price": 280000,
        "inventory": 30,
        "options": {
          "color": "Navy",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP020374",
        "price": 250000,
        "inventory": 14,
        "options": {
          "color": "L",
          "size": "Nâu Đỏ"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008901",
        "price": 250000,
        "inventory": 20,
        "options": {
          "color": "L",
          "size": "ĐEN"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008900",
        "price": 250000,
        "inventory": 0,
        "options": {
          "color": "M",
          "size": "ĐEN"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP020317",
        "price": 250000,
        "inventory": 2,
        "options": {
          "color": "M",
          "size": "NAVY"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008905",
        "price": 250000,
        "inventory": 16,
        "options": {
          "color": "XL",
          "size": "XÁM TIÊU ĐẬM"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008894",
        "price": 250000,
        "inventory": 3,
        "options": {
          "color": "M",
          "size": "MOSSGREEN"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008904",
        "price": 250000,
        "inventory": 15,
        "options": {
          "color": "L",
          "size": "XÁM TIÊU ĐẬM"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008895",
        "price": 250000,
        "inventory": 7,
        "options": {
          "color": "L",
          "size": "MOSSGREEN"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008909",
        "price": 250000,
        "inventory": 9,
        "options": {
          "color": "M",
          "size": "XÁM TIÊU NHẠT"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008907",
        "price": 250000,
        "inventory": 0,
        "options": {
          "color": "L",
          "size": "KEM"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008914",
        "price": 250000,
        "inventory": 0,
        "options": {
          "color": "XL",
          "size": "BLUE GREY"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008902",
        "price": 250000,
        "inventory": 0,
        "options": {
          "color": "XL",
          "size": "ĐEN"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008911",
        "price": 250000,
        "inventory": 0,
        "options": {
          "color": "XL",
          "size": "XÁM TIÊU NHẠT"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008910",
        "price": 250000,
        "inventory": 13,
        "options": {
          "color": "L",
          "size": "XÁM TIÊU NHẠT"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP020373",
        "price": 250000,
        "inventory": 13,
        "options": {
          "color": "M",
          "size": "Nâu Đỏ"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP020319",
        "price": 250000,
        "inventory": 17,
        "options": {
          "color": "XL",
          "size": "NAVY"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008908",
        "price": 250000,
        "inventory": 0,
        "options": {
          "color": "XL",
          "size": "KEM"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008898",
        "price": 250000,
        "inventory": 0,
        "options": {
          "color": "L",
          "size": "XÁM CHÌ"
        }
      },
      {
        "sku": "WHS-507-HDZ-SYMBOL-SP008903",
        "price": 250000,
        "inventory": 12,
        "options": {
          "color": "M",
          "size": "XÁM TIÊU ĐẬM"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/507-hdz-symbol-0.jpg",
        "storageKey": "seed/products/507-hdz-symbol-0.jpg",
        "alt": "Navy",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/507-hdz-symbol-1.jpg",
        "storageKey": "seed/products/507-hdz-symbol-1.jpg",
        "alt": "Navy",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/507-hdz-symbol-2.jpg",
        "storageKey": "seed/products/507-hdz-symbol-2.jpg",
        "alt": "Navy",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/507-hdz-symbol-3.jpg",
        "storageKey": "seed/products/507-hdz-symbol-3.jpg",
        "alt": "Navy",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "ARCH HOODIE ZIP",
    "slug": "arch-hoodie-zip",
    "description": "Mô tả sản phẩm\nChiếc hoodie được phát triển theo tinh thần sporty–casual với phom dáng relaxed, vai rớt nhẹ và phần bo gấu – bo tay ôm vừa, tạo tổng thể cân đối và dễ mặc cho nhiều dáng người. Chất liệu nỉ ép 2 da mang lại bề mặt mịn – đứng form, hạn chế nhăn và tạo cảm giác chắc chắn khi mặc nhưng vẫn giữ được sự thoải mái trong suốt ngày dài.\nĐiểm nhấn nổi bật nằm ở phần logo chữ và số được thêu nổi varsity 3D, sử dụng kỹ thuật chenille ở bề mặt và satin stitch ở phần viền, tạo chiều sâu và hiệu ứng thị giác sắc nét. Khóa kéo chắc chắn, trơn mượt giúp thao tác linh hoạt. Bên trong áo được trang bị túi trong ẩn, tăng tính tiện dụng khi cần mang theo vật dụng quan trọng.\nĐặc điểm nổi bật\nChất liệu nỉ ép 2 da: dày dặn, đứng form, bề mặt mịn và hạn chế nhăn.\nForm relaxed fit: thoải mái, phù hợp nhiều vóc dáng.\nThêu varsity 3D (chenille + satin viền): nổi bật, sắc nét, tạo điểm nhấn mạnh mẽ.\nKhóa kéo chắc chắn: thao tác mượt và bền.\nTúi trong ẩn + túi ngoài: tăng tiện ích và khả năng chứa đồ.\nPhong cách sử dụng\nPhù hợp đi học – đi làm – đi chơi hằng ngày.\nDễ phối với jeans, jogger, wide pants hoặc short.\nHợp phong cách sporty, streetwear hoặc casual tối giản.",
    "status": "active",
    "metaTitle": "ARCH HOODIE ZIP | Whose Studio",
    "metaDescription": "Mô tả sản phẩm\nChiếc hoodie được phát triển theo tinh thần sporty–casual với phom dáng relaxed, vai rớt nhẹ và phần bo gấu – bo tay ôm vừa, tạo tổng thể cân đối",
    "variants": [
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-SP020346",
        "price": 320000,
        "inventory": 2,
        "options": {
          "color": "Đen",
          "size": "M"
        }
      },
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-SP020347",
        "price": 320000,
        "inventory": 9,
        "options": {
          "color": "Đen",
          "size": "L"
        }
      },
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-SP020348",
        "price": 320000,
        "inventory": 3,
        "options": {
          "color": "Đen",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-SP020350",
        "price": 320000,
        "inventory": 4,
        "options": {
          "color": "Xám tiêu đậm",
          "size": "L"
        }
      },
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-SP020354",
        "price": 320000,
        "inventory": 12,
        "options": {
          "color": "Xám Tiêu Nhạt",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-0.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-0.jpg",
        "alt": "Đen",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-1.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-1.jpg",
        "alt": "Đen",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-2.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-2.jpg",
        "alt": "Đen",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-3.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-3.jpg",
        "alt": "Đen",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Arch Hoodie-zip / Tiêu đậm",
    "slug": "arch-hoodie-zip-tieu-dam",
    "description": "Mô tả sản phẩm\nChiếc hoodie được phát triển theo tinh thần sporty–casual với phom dáng relaxed, vai rớt nhẹ và phần bo gấu – bo tay ôm vừa, tạo tổng thể cân đối và dễ mặc cho nhiều dáng người. Chất liệu nỉ ép 2 da mang lại bề mặt mịn – đứng form, hạn chế nhăn và tạo cảm giác chắc chắn khi mặc nhưng vẫn giữ được sự thoải mái trong suốt ngày dài.\nĐiểm nhấn nổi bật nằm ở phần logo chữ và số được thêu nổi varsity 3D, sử dụng kỹ thuật chenille ở bề mặt và satin stitch ở phần viền, tạo chiều sâu và hiệu ứng thị giác sắc nét. Khóa kéo chắc chắn, trơn mượt giúp thao tác linh hoạt. Bên trong áo được trang bị túi trong ẩn, tăng tính tiện dụng khi cần mang theo vật dụng quan trọng.\nĐặc điểm nổi bật\nChất liệu nỉ ép 2 da: dày dặn, đứng form, bề mặt mịn và hạn chế nhăn.\nForm relaxed fit: thoải mái, phù hợp nhiều vóc dáng.\nThêu varsity 3D (chenille + satin viền): nổi bật, sắc nét, tạo điểm nhấn mạnh mẽ.\nKhóa kéo chắc chắn: thao tác mượt và bền.\nTúi trong ẩn + túi ngoài: tăng tiện ích và khả năng chứa đồ.\nPhong cách sử dụng\nPhù hợp đi học – đi làm – đi chơi hằng ngày.\nDễ phối với jeans, jogger, wide pants hoặc short.\nHợp phong cách sporty, streetwear hoặc casual tối giản.",
    "status": "active",
    "metaTitle": "Arch Hoodie-zip / Tiêu đậm | Whose Studio",
    "metaDescription": "Mô tả sản phẩm\nChiếc hoodie được phát triển theo tinh thần sporty–casual với phom dáng relaxed, vai rớt nhẹ và phần bo gấu – bo tay ôm vừa, tạo tổng thể cân đối",
    "variants": [
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-TIEU-XAM-TIEU-AM-S",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Xám tiêu đậm",
          "size": "S"
        }
      },
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-TIEU-XAM-TIEU-AM-M",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Xám tiêu đậm",
          "size": "M"
        }
      },
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-TIEU-XAM-TIEU-AM-L",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Xám tiêu đậm",
          "size": "L"
        }
      },
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-TIEU-XAM-TIEU-AM-XL",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Xám tiêu đậm",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-tieu-dam-0.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-tieu-dam-0.jpg",
        "alt": "Xám tiêu đậm",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-tieu-dam-1.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-tieu-dam-1.jpg",
        "alt": "Xám tiêu đậm",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-tieu-dam-2.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-tieu-dam-2.jpg",
        "alt": "Xám tiêu đậm",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-tieu-dam-3.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-tieu-dam-3.jpg",
        "alt": "Xám tiêu đậm",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Arch Hoodie-zip / Xám tiêu nhạt",
    "slug": "arch-hoodie-zip-tieu-nhat",
    "description": "Mô tả sản phẩm\nChiếc hoodie được phát triển theo tinh thần sporty–casual với phom dáng relaxed, vai rớt nhẹ và phần bo gấu – bo tay ôm vừa, tạo tổng thể cân đối và dễ mặc cho nhiều dáng người. Chất liệu nỉ ép 2 da mang lại bề mặt mịn – đứng form, hạn chế nhăn và tạo cảm giác chắc chắn khi mặc nhưng vẫn giữ được sự thoải mái trong suốt ngày dài.\nĐiểm nhấn nổi bật nằm ở phần logo chữ và số được thêu nổi varsity 3D, sử dụng kỹ thuật chenille ở bề mặt và satin stitch ở phần viền, tạo chiều sâu và hiệu ứng thị giác sắc nét. Khóa kéo chắc chắn, trơn mượt giúp thao tác linh hoạt. Bên trong áo được trang bị túi trong ẩn, tăng tính tiện dụng khi cần mang theo vật dụng quan trọng.\nĐặc điểm nổi bật\nChất liệu nỉ ép 2 da: dày dặn, đứng form, bề mặt mịn và hạn chế nhăn.\nForm relaxed fit: thoải mái, phù hợp nhiều vóc dáng.\nThêu varsity 3D (chenille + satin viền): nổi bật, sắc nét, tạo điểm nhấn mạnh mẽ.\nKhóa kéo chắc chắn: thao tác mượt và bền.\nTúi trong ẩn + túi ngoài: tăng tiện ích và khả năng chứa đồ.\nPhong cách sử dụng\nPhù hợp đi học – đi làm – đi chơi hằng ngày.\nDễ phối với jeans, jogger, wide pants hoặc short.\nHợp phong cách sporty, streetwear hoặc casual tối giản.",
    "status": "active",
    "metaTitle": "Arch Hoodie-zip / Xám tiêu nhạt | Whose Studio",
    "metaDescription": "Mô tả sản phẩm\nChiếc hoodie được phát triển theo tinh thần sporty–casual với phom dáng relaxed, vai rớt nhẹ và phần bo gấu – bo tay ôm vừa, tạo tổng thể cân đối",
    "variants": [
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-TIEU-SP020346",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Xám tiêu nhạt",
          "size": "M"
        }
      },
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-TIEU-SP020347",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Xám tiêu nhạt",
          "size": "L"
        }
      },
      {
        "sku": "WHS-ARCH-HOODIE-ZIP-TIEU-SP020348",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Xám tiêu nhạt",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-tieu-nhat-0.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-tieu-nhat-0.jpg",
        "alt": "Xám tiêu nhạt",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-tieu-nhat-1.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-tieu-nhat-1.jpg",
        "alt": "Xám tiêu nhạt",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-tieu-nhat-2.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-tieu-nhat-2.jpg",
        "alt": "Xám tiêu nhạt",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/arch-hoodie-zip-tieu-nhat-3.jpg",
        "storageKey": "seed/products/arch-hoodie-zip-tieu-nhat-3.jpg",
        "alt": "Xám tiêu nhạt",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Blank Sweater Premium Cotton 350GSM / Black",
    "slug": "blank-sweater-premium-cotton-350gsm-black",
    "description": "Chiếc sweatshirt được phát triển từ chất liệu nỉ bông cotton premium 350GSM, mang lại cảm giác dày dặn, ấm áp nhưng vẫn mềm mịn khi chạm vào. Chất liệu cotton tỉ lệ cao giúp áo thoáng khí, tạo sự thoải mái khi mặc cả ngày mà không bí hay nặng.\nPhom relaxed với vai rớt nhẹ, bo gấu – bo tay ôm vừa, giúp tổng thể trông gọn nhưng vẫn giữ được nét casual hiện đại. Logo thêu tối giản tạo điểm nhấn tinh tế mà không làm mất đi sự sạch sẽ của thiết kế.\nĐặc điểm nổi bật\nChất liệu 350GSM: dày – chắc – giữ form tốt.\nNỉ bông cotton premium mềm, ấm, thoáng.\nForm relaxed fit hợp nhiều vóc dáng.\nLogo thêu nổi tinh tế ở trước ngực.\nBo gấu và bo tay chắc chắn, đàn hồi tốt.\nDễ phối với mọi item: quần jeans, quần kaki, jogger…\nPhong cách gợi ý\nOutfit tối giản với quần straight hoặc wide.\nLayer với áo thun cổ tròn, khoác ngoài denim jacket/hoodie zip.\nPhù hợp đi học – đi làm – đi chơi mỗi ngày.",
    "status": "active",
    "metaTitle": "Blank Sweater Premium Cotton 350GSM / Black | Whose Studio",
    "metaDescription": "Chiếc sweatshirt được phát triển từ chất liệu nỉ bông cotton premium 350GSM, mang lại cảm giác dày dặn, ấm áp nhưng vẫn mềm mịn khi chạm vào. Chất liệu cotton t",
    "variants": [
      {
        "sku": "WHS-BLANK-SWEATER-PREMIU-BLACK-M",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "M"
        }
      },
      {
        "sku": "WHS-BLANK-SWEATER-PREMIU-BLACK-L",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "L"
        }
      },
      {
        "sku": "WHS-BLANK-SWEATER-PREMIU-BLACK-XL",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blank-sweater-premium-cotton-350gsm-black-0.jpg",
        "storageKey": "seed/products/blank-sweater-premium-cotton-350gsm-black-0.jpg",
        "alt": "Black",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blank-sweater-premium-cotton-350gsm-black-1.jpg",
        "storageKey": "seed/products/blank-sweater-premium-cotton-350gsm-black-1.jpg",
        "alt": "Black",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blank-sweater-premium-cotton-350gsm-black-2.jpg",
        "storageKey": "seed/products/blank-sweater-premium-cotton-350gsm-black-2.jpg",
        "alt": "Black",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blank-sweater-premium-cotton-350gsm-black-3.jpg",
        "storageKey": "seed/products/blank-sweater-premium-cotton-350gsm-black-3.jpg",
        "alt": "Black",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "AIRFRAME JACKET",
    "slug": "airframe-jacket",
    "description": "* Tên Sản Phẩm: AIRFRAME JACKET - Áo Khoác Dù Nhăn Cổ Đứng Whose Studio\n* Chất Liệu: Crinkle Nylon 3 Lớp Cao Cấp\n* Form: Boxy Fit\nAIRFRAME JACKET được phát triển từ cảm hứng của những thiết kế outerwear kỹ thuật hiện đại, tập trung vào sự tối giản, gọn gàng và tính ứng dụng trong cuộc sống hằng ngày.\nSản phẩm sử dụng chất liệu dù nhăn (Crinkle Nylon) với bề mặt texture tự nhiên, mang lại cảm giác nhẹ, thoải mái và giữ form tốt khi sử dụng. Thiết kế cổ đứng cao kết hợp cùng logo kim loại nổi ở ngực tạo điểm nhấn tinh tế nhưng vẫn giữ được tinh thần tối giản đặc trưng.\nForm Boxy Fit rộng vừa phải, phù hợp với nhiều dáng người và dễ dàng phối cùng nhiều phong cách từ streetwear đến daily wear.\nThiết kế tối giản - Chất liệu cao cấp - Dễ phối đồ hằng ngày.\n* Đặc Điểm Nổi Bật:\n- Chất liệu dù nhăn Crinkle Nylon cao cấp.\n- Kết cấu 3 lớp dày dặn, giữ form tốt.\n- Form Boxy Fit hiện đại.\n- Cổ đứng cao tạo điểm nhấn mạnh mẽ.\n- Logo kim loại nổi ở ngực trái.\n- Bo tay và bo lai giúp áo luôn ổn định form.\n- Khóa kéo trung tâm tối giản, gọn gàng.\n- Trọng lượng nhẹ, phù hợp sử dụng hằng ngày.\n* Hướng Dẫn Bảo Quản:\n- Giặt tay hoặc giặt máy chế độ nhẹ.\n- Không sử dụng thuốc tẩy.\n- Hạn chế sấy ở nhiệt độ cao.\n- Phơi nơi khô ráo, thoáng mát.\nNếu có bất kỳ vấn đề nào về sản phẩm, vui lòng liên hệ shop để được hỗ trợ nhanh nhất. Cảm ơn bạn đã tin tưởng và lựa chọn Whose Studio!",
    "status": "active",
    "metaTitle": "AIRFRAME JACKET | Whose Studio",
    "metaDescription": "* Tên Sản Phẩm: AIRFRAME JACKET - Áo Khoác Dù Nhăn Cổ Đứng Whose Studio\n* Chất Liệu: Crinkle Nylon 3 Lớp Cao Cấp\n* Form: Boxy Fit\nAIRFRAME JACKET được phát triể",
    "variants": [
      {
        "sku": "WHS-AIRFRAME-JACKET-BLACK-M",
        "price": 409000,
        "compareAtPrice": 500000,
        "inventory": 0,
        "options": {
          "color": "BLACK",
          "size": "M"
        }
      },
      {
        "sku": "WHS-AIRFRAME-JACKET-BLACK-L",
        "price": 409000,
        "compareAtPrice": 500000,
        "inventory": 0,
        "options": {
          "color": "BLACK",
          "size": "L"
        }
      },
      {
        "sku": "WHS-AIRFRAME-JACKET-BLACK-XL",
        "price": 409000,
        "compareAtPrice": 500000,
        "inventory": 0,
        "options": {
          "color": "BLACK",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-AIRFRAME-JACKET-BEIGE-M",
        "price": 409000,
        "compareAtPrice": 500000,
        "inventory": 0,
        "options": {
          "color": "Beige",
          "size": "M"
        }
      },
      {
        "sku": "WHS-AIRFRAME-JACKET-BEIGE-L",
        "price": 409000,
        "compareAtPrice": 500000,
        "inventory": 0,
        "options": {
          "color": "Beige",
          "size": "L"
        }
      },
      {
        "sku": "WHS-AIRFRAME-JACKET-BEIGE-XL",
        "price": 409000,
        "compareAtPrice": 500000,
        "inventory": 0,
        "options": {
          "color": "Beige",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-AIRFRAME-JACKET-WHITE-M",
        "price": 409000,
        "compareAtPrice": 500000,
        "inventory": 0,
        "options": {
          "color": "White",
          "size": "M"
        }
      },
      {
        "sku": "WHS-AIRFRAME-JACKET-WHITE-L",
        "price": 409000,
        "compareAtPrice": 500000,
        "inventory": 0,
        "options": {
          "color": "White",
          "size": "L"
        }
      },
      {
        "sku": "WHS-AIRFRAME-JACKET-WHITE-XL",
        "price": 409000,
        "compareAtPrice": 500000,
        "inventory": 0,
        "options": {
          "color": "White",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/airframe-jacket-0.png",
        "storageKey": "seed/products/airframe-jacket-0.png",
        "alt": "AIRFRAME JACKET",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/airframe-jacket-1.png",
        "storageKey": "seed/products/airframe-jacket-1.png",
        "alt": "AIRFRAME JACKET",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/airframe-jacket-2.png",
        "storageKey": "seed/products/airframe-jacket-2.png",
        "alt": "AIRFRAME JACKET",
        "sortOrder": 2
      }
    ]
  },
  {
    "name": "Denim Jacket / Đen",
    "slug": "denim-jacket-den",
    "description": "Chiếc denim jacket được phát triển trên chất liệu jeans dày dặn, giữ form tốt nhưng vẫn tạo cảm giác thoải mái khi mặc hằng ngày. Form dáng boxy vừa, dễ layer với tee, hoodie hoặc knitwear, phù hợp cả đi chơi lẫn đi làm.\nToàn bộ áo được hoàn thiện bằng đường may chỉ nổi tương phản, tạo điểm nhấn mạnh mẽ, sắc nét và mang tinh thần workwear cổ điển. Mặt trước gồm hai túi flap dạng hộp, kết hợp cùng hệ thống nút kim loại bạc mờ mang cảm giác hiện đại và bền bỉ.\nPhần vai và thân áo được thiết kế với các mảng cắt xếp đối xứng, giúp jacket đứng phom, tạo cấu trúc rõ ràng khi mặc. Cổ áo tiêu chuẩn, tay dài có nút điều chỉnh giúp người dùng dễ tuỳ chỉnh phom tay theo nhu cầu.\nĐẶC ĐIỂM NỔI BẬTVải denim dày, đứng phom, bền và ít nhăn.\nForm boxy hiện đại, dễ phối với hầu hết outfit.\nĐường chỉ nổi tương phản, tăng chiều sâu và độ sắc nét của thiết kế.\nNút kim loại cao cấp, chắc chắn – tăng tuổi thọ sản phẩm.\nHai túi ngực flap + túi bên tiện dụng, mang vibe workwear cổ điển.\nPhù hợp để layer với tee, sweater, hoodie cho phong cách casual & streetwear.",
    "status": "active",
    "metaTitle": "Denim Jacket / Đen | Whose Studio",
    "metaDescription": "Chiếc denim jacket được phát triển trên chất liệu jeans dày dặn, giữ form tốt nhưng vẫn tạo cảm giác thoải mái khi mặc hằng ngày. Form dáng boxy vừa, dễ layer v",
    "variants": [
      {
        "sku": "WHS-DENIM-JACKET-DEN-EN-M",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Đen",
          "size": "M"
        }
      },
      {
        "sku": "WHS-DENIM-JACKET-DEN-EN-L",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Đen",
          "size": "L"
        }
      },
      {
        "sku": "WHS-DENIM-JACKET-DEN-EN-XL",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Đen",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-den-0.jpg",
        "storageKey": "seed/products/denim-jacket-den-0.jpg",
        "alt": "Black",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-den-1.jpg",
        "storageKey": "seed/products/denim-jacket-den-1.jpg",
        "alt": "Đen",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-den-2.jpg",
        "storageKey": "seed/products/denim-jacket-den-2.jpg",
        "alt": "Đen",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-den-3.jpg",
        "storageKey": "seed/products/denim-jacket-den-3.jpg",
        "alt": "Đen",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Denim Jacket / Indigo",
    "slug": "denim-jacket-indigo",
    "description": "Chiếc denim jacket được phát triển trên chất liệu jeans dày dặn, giữ form tốt nhưng vẫn tạo cảm giác thoải mái khi mặc hằng ngày. Form dáng boxy vừa, dễ layer với tee, hoodie hoặc knitwear, phù hợp cả đi chơi lẫn đi làm.\nToàn bộ áo được hoàn thiện bằng đường may chỉ nổi tương phản, tạo điểm nhấn mạnh mẽ, sắc nét và mang tinh thần workwear cổ điển. Mặt trước gồm hai túi flap dạng hộp, kết hợp cùng hệ thống nút kim loại bạc mờ mang cảm giác hiện đại và bền bỉ.\nPhần vai và thân áo được thiết kế với các mảng cắt xếp đối xứng, giúp jacket đứng phom, tạo cấu trúc rõ ràng khi mặc. Cổ áo tiêu chuẩn, tay dài có nút điều chỉnh giúp người dùng dễ tuỳ chỉnh phom tay theo nhu cầu.\nĐẶC ĐIỂM NỔI BẬTVải denim dày, đứng phom, bền và ít nhăn.\nForm boxy hiện đại, dễ phối với hầu hết outfit.\nĐường chỉ nổi tương phản, tăng chiều sâu và độ sắc nét của thiết kế.\nNút kim loại cao cấp, chắc chắn – tăng tuổi thọ sản phẩm.\nHai túi ngực flap + túi bên tiện dụng, mang vibe workwear cổ điển.\nPhù hợp để layer với tee, sweater, hoodie cho phong cách casual & streetwear.",
    "status": "active",
    "metaTitle": "Denim Jacket / Indigo | Whose Studio",
    "metaDescription": "Chiếc denim jacket được phát triển trên chất liệu jeans dày dặn, giữ form tốt nhưng vẫn tạo cảm giác thoải mái khi mặc hằng ngày. Form dáng boxy vừa, dễ layer v",
    "variants": [
      {
        "sku": "WHS-DENIM-JACKET-INDIGO-INDIGO-M",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Indigo",
          "size": "M"
        }
      },
      {
        "sku": "WHS-DENIM-JACKET-INDIGO-INDIGO-L",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Indigo",
          "size": "L"
        }
      },
      {
        "sku": "WHS-DENIM-JACKET-INDIGO-INDIGO-XL",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Indigo",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-indigo-0.jpg",
        "storageKey": "seed/products/denim-jacket-indigo-0.jpg",
        "alt": "Indigo",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-indigo-1.jpg",
        "storageKey": "seed/products/denim-jacket-indigo-1.jpg",
        "alt": "Indigo",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-indigo-2.jpg",
        "storageKey": "seed/products/denim-jacket-indigo-2.jpg",
        "alt": "Indigo",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-indigo-3.jpg",
        "storageKey": "seed/products/denim-jacket-indigo-3.jpg",
        "alt": "Indigo",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Denim Jacket / Kem",
    "slug": "denim-jacket-kem",
    "description": "Chiếc denim jacket được phát triển trên chất liệu jeans dày dặn, giữ form tốt nhưng vẫn tạo cảm giác thoải mái khi mặc hằng ngày. Form dáng boxy vừa, dễ layer với tee, hoodie hoặc knitwear, phù hợp cả đi chơi lẫn đi làm.\nToàn bộ áo được hoàn thiện bằng đường may chỉ nổi tương phản, tạo điểm nhấn mạnh mẽ, sắc nét và mang tinh thần workwear cổ điển. Mặt trước gồm hai túi flap dạng hộp, kết hợp cùng hệ thống nút kim loại bạc mờ mang cảm giác hiện đại và bền bỉ.\nPhần vai và thân áo được thiết kế với các mảng cắt xếp đối xứng, giúp jacket đứng phom, tạo cấu trúc rõ ràng khi mặc. Cổ áo tiêu chuẩn, tay dài có nút điều chỉnh giúp người dùng dễ tuỳ chỉnh phom tay theo nhu cầu.\nĐẶC ĐIỂM NỔI BẬTVải denim dày, đứng phom, bền và ít nhăn.\nForm boxy hiện đại, dễ phối với hầu hết outfit.\nĐường chỉ nổi tương phản, tăng chiều sâu và độ sắc nét của thiết kế.\nNút kim loại cao cấp, chắc chắn – tăng tuổi thọ sản phẩm.\nHai túi ngực flap + túi bên tiện dụng, mang vibe workwear cổ điển.\nPhù hợp để layer với tee, sweater, hoodie cho phong cách casual & streetwear.",
    "status": "active",
    "metaTitle": "Denim Jacket / Kem | Whose Studio",
    "metaDescription": "Chiếc denim jacket được phát triển trên chất liệu jeans dày dặn, giữ form tốt nhưng vẫn tạo cảm giác thoải mái khi mặc hằng ngày. Form dáng boxy vừa, dễ layer v",
    "variants": [
      {
        "sku": "WHS-DENIM-JACKET-KEM-KEM-M",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Kem",
          "size": "M"
        }
      },
      {
        "sku": "WHS-DENIM-JACKET-KEM-KEM-L",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Kem",
          "size": "L"
        }
      },
      {
        "sku": "WHS-DENIM-JACKET-KEM-KEM-XL",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Kem",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-kem-0.jpg",
        "storageKey": "seed/products/denim-jacket-kem-0.jpg",
        "alt": "Kem",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-kem-1.jpg",
        "storageKey": "seed/products/denim-jacket-kem-1.jpg",
        "alt": "Kem",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-kem-2.jpg",
        "storageKey": "seed/products/denim-jacket-kem-2.jpg",
        "alt": "Kem",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-kem-3.jpg",
        "storageKey": "seed/products/denim-jacket-kem-3.jpg",
        "alt": "Kem",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Denim Jacket / Rêu",
    "slug": "denim-jacket-reu",
    "description": "Chiếc denim jacket được phát triển trên chất liệu jeans dày dặn, giữ form tốt nhưng vẫn tạo cảm giác thoải mái khi mặc hằng ngày. Form dáng boxy vừa, dễ layer với tee, hoodie hoặc knitwear, phù hợp cả đi chơi lẫn đi làm.\nToàn bộ áo được hoàn thiện bằng đường may chỉ nổi tương phản, tạo điểm nhấn mạnh mẽ, sắc nét và mang tinh thần workwear cổ điển. Mặt trước gồm hai túi flap dạng hộp, kết hợp cùng hệ thống nút kim loại bạc mờ mang cảm giác hiện đại và bền bỉ.\nPhần vai và thân áo được thiết kế với các mảng cắt xếp đối xứng, giúp jacket đứng phom, tạo cấu trúc rõ ràng khi mặc. Cổ áo tiêu chuẩn, tay dài có nút điều chỉnh giúp người dùng dễ tuỳ chỉnh phom tay theo nhu cầu.\nĐẶC ĐIỂM NỔI BẬTVải denim dày, đứng phom, bền và ít nhăn.\nForm boxy hiện đại, dễ phối với hầu hết outfit.\nĐường chỉ nổi tương phản, tăng chiều sâu và độ sắc nét của thiết kế.\nNút kim loại cao cấp, chắc chắn – tăng tuổi thọ sản phẩm.\nHai túi ngực flap + túi bên tiện dụng, mang vibe workwear cổ điển.\nPhù hợp để layer với tee, sweater, hoodie cho phong cách casual & streetwear.",
    "status": "active",
    "metaTitle": "Denim Jacket / Rêu | Whose Studio",
    "metaDescription": "Chiếc denim jacket được phát triển trên chất liệu jeans dày dặn, giữ form tốt nhưng vẫn tạo cảm giác thoải mái khi mặc hằng ngày. Form dáng boxy vừa, dễ layer v",
    "variants": [
      {
        "sku": "WHS-DENIM-JACKET-REU-REU-M",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Rêu",
          "size": "M"
        }
      },
      {
        "sku": "WHS-DENIM-JACKET-REU-REU-L",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Rêu",
          "size": "L"
        }
      },
      {
        "sku": "WHS-DENIM-JACKET-REU-REU-XL",
        "price": 320000,
        "inventory": 0,
        "options": {
          "color": "Rêu",
          "size": "XL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-reu-0.jpg",
        "storageKey": "seed/products/denim-jacket-reu-0.jpg",
        "alt": "Rêu",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-reu-1.jpg",
        "storageKey": "seed/products/denim-jacket-reu-1.jpg",
        "alt": "Rêu",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-reu-2.jpg",
        "storageKey": "seed/products/denim-jacket-reu-2.jpg",
        "alt": "Rêu",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/denim-jacket-reu-3.jpg",
        "storageKey": "seed/products/denim-jacket-reu-3.jpg",
        "alt": "Rêu",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Cap Metal Logo Whose / Black",
    "slug": "cap-metal-logo-whose-black",
    "description": "Chiếc mũ denim distressed của Whose được phát triển trên nền chất liệu cotton denim cao cấp, xử lý wash loang độc bản kết hợp các mảng rách thủ công tạo hiệu ứng bụi bặm – cá tính, mang đúng tinh thần streetwear đương đại. Tone màu xám–be loang được xử lý bằng kỹ thuật wash mạnh, tạo cảm giác như một chiếc mũ đã trải qua thời gian và câu chuyện riêng.\nPhần logo kim loại WHOOSE được đặt tinh tế ở mặt trước, hoàn thiện bằng lớp xi mờ sang trọng, giúp tổng thể vừa cá tính vừa giữ được sự cao cấp của sản phẩm. Vành mũ và thân mũ được làm rách có kiểm soát, sợi vải bung tự nhiên nhưng vẫn đảm bảo độ bền khi sử dụng lâu dài.\nMũ có form ôm vừa đầu, dễ chỉnh size với khoá sau, phù hợp nhiều dáng mặt và phong cách. Đây là item dễ phối đồ – từ denim jacket, áo thun trơn đến các outfit cá tính theo hơi hướng workwear, grunge hoặc vintage street.\nĐặc điểm nổi bật\nDenim cotton cao cấp: chất liệu dày dặn – thoáng – bền.\nXử lý wash loang thủ công: mỗi chiếc có pattern wash riêng, mang tính độc bản.\nHiệu ứng rách (distressed): bố trí có chủ đích, tạo vibe worn-out tự nhiên nhưng vẫn chắc chắn.\nLogo kim loại WHOOSE: chi tiết điểm nhấn sang trọng, sắc nét.\nDễ chỉnh size: khoá gài chắc chắn, phù hợp mọi form đầu.\nDễ phối: hợp từ outfit streetwear đến Y2K hoặc phong cách vintage bụi.",
    "status": "active",
    "metaTitle": "Cap Metal Logo Whose / Black | Whose Studio",
    "metaDescription": "Chiếc mũ denim distressed của Whose được phát triển trên nền chất liệu cotton denim cao cấp, xử lý wash loang độc bản kết hợp các mảng rách thủ công tạo hiệu ứn",
    "variants": [
      {
        "sku": "WHS-CAP-METAL-LOGO-WHOSE-BLACK-1",
        "price": 220000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "1"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-black-0.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-black-0.jpg",
        "alt": "Black",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-black-1.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-black-1.jpg",
        "alt": "Black",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-black-2.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-black-2.jpg",
        "alt": "Black",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-black-3.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-black-3.jpg",
        "alt": "Black",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Cap Metal Logo Whose / Vàng",
    "slug": "cap-metal-logo-whose-vang",
    "description": "Chiếc mũ denim distressed của Whose được phát triển trên nền chất liệu cotton denim cao cấp, xử lý wash loang độc bản kết hợp các mảng rách thủ công tạo hiệu ứng bụi bặm – cá tính, mang đúng tinh thần streetwear đương đại. Tone màu xám–be loang được xử lý bằng kỹ thuật wash mạnh, tạo cảm giác như một chiếc mũ đã trải qua thời gian và câu chuyện riêng.\nPhần logo kim loại WHOOSE được đặt tinh tế ở mặt trước, hoàn thiện bằng lớp xi mờ sang trọng, giúp tổng thể vừa cá tính vừa giữ được sự cao cấp của sản phẩm. Vành mũ và thân mũ được làm rách có kiểm soát, sợi vải bung tự nhiên nhưng vẫn đảm bảo độ bền khi sử dụng lâu dài.\nMũ có form ôm vừa đầu, dễ chỉnh size với khoá sau, phù hợp nhiều dáng mặt và phong cách. Đây là item dễ phối đồ – từ denim jacket, áo thun trơn đến các outfit cá tính theo hơi hướng workwear, grunge hoặc vintage street.\nĐặc điểm nổi bật\nDenim cotton cao cấp: chất liệu dày dặn – thoáng – bền.\nXử lý wash loang thủ công: mỗi chiếc có pattern wash riêng, mang tính độc bản.\nHiệu ứng rách (distressed): bố trí có chủ đích, tạo vibe worn-out tự nhiên nhưng vẫn chắc chắn.\nLogo kim loại WHOOSE: chi tiết điểm nhấn sang trọng, sắc nét.\nDễ chỉnh size: khoá gài chắc chắn, phù hợp mọi form đầu.\nDễ phối: hợp từ outfit streetwear đến Y2K hoặc phong cách vintage bụi.",
    "status": "active",
    "metaTitle": "Cap Metal Logo Whose / Vàng | Whose Studio",
    "metaDescription": "Chiếc mũ denim distressed của Whose được phát triển trên nền chất liệu cotton denim cao cấp, xử lý wash loang độc bản kết hợp các mảng rách thủ công tạo hiệu ứn",
    "variants": [
      {
        "sku": "WHS-CAP-METAL-LOGO-WHOSE-VANG-1",
        "price": 220000,
        "inventory": 0,
        "options": {
          "color": "Vàng",
          "size": "1"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-vang-0.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-vang-0.jpg",
        "alt": "Vàng",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-vang-1.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-vang-1.jpg",
        "alt": "Vàng",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-vang-2.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-vang-2.jpg",
        "alt": "Vàng",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-vang-3.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-vang-3.jpg",
        "alt": "Vàng",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Cap Metal Logo Whose / Xanh",
    "slug": "cap-metal-logo-whose-xanh",
    "description": "Chiếc mũ denim distressed của Whose được phát triển trên nền chất liệu cotton denim cao cấp, xử lý wash loang độc bản kết hợp các mảng rách thủ công tạo hiệu ứng bụi bặm – cá tính, mang đúng tinh thần streetwear đương đại. Tone màu xám–be loang được xử lý bằng kỹ thuật wash mạnh, tạo cảm giác như một chiếc mũ đã trải qua thời gian và câu chuyện riêng.\nPhần logo kim loại WHOOSE được đặt tinh tế ở mặt trước, hoàn thiện bằng lớp xi mờ sang trọng, giúp tổng thể vừa cá tính vừa giữ được sự cao cấp của sản phẩm. Vành mũ và thân mũ được làm rách có kiểm soát, sợi vải bung tự nhiên nhưng vẫn đảm bảo độ bền khi sử dụng lâu dài.\nMũ có form ôm vừa đầu, dễ chỉnh size với khoá sau, phù hợp nhiều dáng mặt và phong cách. Đây là item dễ phối đồ – từ denim jacket, áo thun trơn đến các outfit cá tính theo hơi hướng workwear, grunge hoặc vintage street.\nĐặc điểm nổi bật\nDenim cotton cao cấp: chất liệu dày dặn – thoáng – bền.\nXử lý wash loang thủ công: mỗi chiếc có pattern wash riêng, mang tính độc bản.\nHiệu ứng rách (distressed): bố trí có chủ đích, tạo vibe worn-out tự nhiên nhưng vẫn chắc chắn.\nLogo kim loại WHOOSE: chi tiết điểm nhấn sang trọng, sắc nét.\nDễ chỉnh size: khoá gài chắc chắn, phù hợp mọi form đầu.\nDễ phối: hợp từ outfit streetwear đến Y2K hoặc phong cách vintage bụi.",
    "status": "active",
    "metaTitle": "Cap Metal Logo Whose / Xanh | Whose Studio",
    "metaDescription": "Chiếc mũ denim distressed của Whose được phát triển trên nền chất liệu cotton denim cao cấp, xử lý wash loang độc bản kết hợp các mảng rách thủ công tạo hiệu ứn",
    "variants": [
      {
        "sku": "WHS-CAP-METAL-LOGO-WHOSE-XANH-1",
        "price": 220000,
        "inventory": 0,
        "options": {
          "color": "Xanh",
          "size": "1"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-xanh-0.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-xanh-0.jpg",
        "alt": "Xanh",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-xanh-1.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-xanh-1.jpg",
        "alt": "Xanh",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-xanh-2.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-xanh-2.jpg",
        "alt": "Xanh",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-xanh-3.jpg",
        "storageKey": "seed/products/cap-metal-logo-whose-xanh-3.jpg",
        "alt": "Xanh",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Frost Knit Scraft 270GSM / Black",
    "slug": "frost-knit-scraft-270gsm-black",
    "description": "Khăn dệt WHSERS được phát triển theo tiêu chí ấm – mềm – bền – sắc nét, phù hợp với cả thời tiết lạnh lẫn nhu cầu styling hằng ngày.\nSử dụng chất liệu dệt dày 270GSM, dày hơn 30–40% so với các dòng khăn giá rẻ phổ biến trên thị trường, cho cảm giác giữ nhiệt vượt trội nhưng vẫn thoải mái khi mang lâu.\nBề mặt khăn mềm mịn, sờ êm, an toàn cho da và hạn chế xù lông trong quá trình sử dụng. Logo WHSERS® và WHOSECULTURE® được dệt trực tiếp vào nền vải, cho độ sắc nét cao, không bong tróc như hình in.\nKích thước: 185 × 35 cm – tối ưu cho việc quàng 1 vòng, 2 vòng, hoặc styling theo phong cách streetwear.\nChi tiết nổi bậtChất liệu knit dày 270GSM – giữ ấm tốt, đứng form, bền khi giặt.\nDày hơn 30–40% so với khăn giá rẻ, giúp trải nghiệm sử dụng vượt trội.\nBề mặt mịn – êm – siêu ấm, phù hợp mùa lạnh hoặc đi du lịch.\nLogo dệt WHSERS® và WHOSECULTURE® sắc nét, độ bền cao.\nKích thước chuẩn 185 × 35 cm, dễ phối với áo khoác, trench coat, hoodie.",
    "status": "active",
    "metaTitle": "Frost Knit Scraft 270GSM / Black | Whose Studio",
    "metaDescription": "Khăn dệt WHSERS được phát triển theo tiêu chí ấm – mềm – bền – sắc nét, phù hợp với cả thời tiết lạnh lẫn nhu cầu styling hằng ngày.\nSử dụng chất liệu dệt dày 2",
    "variants": [
      {
        "sku": "WHS-FROST-KNIT-SCRAFT-27-BLACK-185X35",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "185x35"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/frost-knit-scraft-270gsm-black-0.jpg",
        "storageKey": "seed/products/frost-knit-scraft-270gsm-black-0.jpg",
        "alt": "Black",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/frost-knit-scraft-270gsm-black-1.jpg",
        "storageKey": "seed/products/frost-knit-scraft-270gsm-black-1.jpg",
        "alt": "Black",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/frost-knit-scraft-270gsm-black-2.jpg",
        "storageKey": "seed/products/frost-knit-scraft-270gsm-black-2.jpg",
        "alt": "Black",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/frost-knit-scraft-270gsm-black-3.jpg",
        "storageKey": "seed/products/frost-knit-scraft-270gsm-black-3.jpg",
        "alt": "Black",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Frost Knit Scraft 270GSM / Grey",
    "slug": "frost-knit-scraft-270gsm-grey",
    "description": "Khăn dệt WHSERS được phát triển theo tiêu chí ấm – mềm – bền – sắc nét, phù hợp với cả thời tiết lạnh lẫn nhu cầu styling hằng ngày.\nSử dụng chất liệu dệt dày 270GSM, dày hơn 30–40% so với các dòng khăn giá rẻ phổ biến trên thị trường, cho cảm giác giữ nhiệt vượt trội nhưng vẫn thoải mái khi mang lâu.\nBề mặt khăn mềm mịn, sờ êm, an toàn cho da và hạn chế xù lông trong quá trình sử dụng. Logo WHSERS® và WHOSECULTURE® được dệt trực tiếp vào nền vải, cho độ sắc nét cao, không bong tróc như hình in.\nKích thước: 185 × 35 cm – tối ưu cho việc quàng 1 vòng, 2 vòng, hoặc styling theo phong cách streetwear.\nChi tiết nổi bậtChất liệu knit dày 270GSM – giữ ấm tốt, đứng form, bền khi giặt.\nDày hơn 30–40% so với khăn giá rẻ, giúp trải nghiệm sử dụng vượt trội.\nBề mặt mịn – êm – siêu ấm, phù hợp mùa lạnh hoặc đi du lịch.\nLogo dệt WHSERS® và WHOSECULTURE® sắc nét, độ bền cao.\nKích thước chuẩn 185 × 35 cm, dễ phối với áo khoác, trench coat, hoodie.",
    "status": "active",
    "metaTitle": "Frost Knit Scraft 270GSM / Grey | Whose Studio",
    "metaDescription": "Khăn dệt WHSERS được phát triển theo tiêu chí ấm – mềm – bền – sắc nét, phù hợp với cả thời tiết lạnh lẫn nhu cầu styling hằng ngày.\nSử dụng chất liệu dệt dày 2",
    "variants": [
      {
        "sku": "WHS-FROST-KNIT-SCRAFT-27-GREY-185X35",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Grey",
          "size": "185x35"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/frost-knit-scraft-270gsm-grey-0.jpg",
        "storageKey": "seed/products/frost-knit-scraft-270gsm-grey-0.jpg",
        "alt": "Grey",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/frost-knit-scraft-270gsm-grey-1.jpg",
        "storageKey": "seed/products/frost-knit-scraft-270gsm-grey-1.jpg",
        "alt": "Grey",
        "sortOrder": 1
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/frost-knit-scraft-270gsm-grey-2.jpg",
        "storageKey": "seed/products/frost-knit-scraft-270gsm-grey-2.jpg",
        "alt": "Grey",
        "sortOrder": 2
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/frost-knit-scraft-270gsm-grey-3.jpg",
        "storageKey": "seed/products/frost-knit-scraft-270gsm-grey-3.jpg",
        "alt": "Grey",
        "sortOrder": 3
      }
    ]
  },
  {
    "name": "Wide Straight Jeans > Dáng suông > Beige",
    "slug": "wide-straight-jeans-dang-suong-beige",
    "description": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông xuống ống, mang lại sự thoải mái nhưng vẫn giữ được sự gọn gàng và cân đối khi mặc.\nChất liệu jeans kaki đứng form, bền, có độ mềm vừa phải để thoải mái vận động suốt ngày dài.\nĐặc điểm nổi bậtForm Wide Straight: suông thẳng, rộng vừa, không phồng.\nChất liệu jeans kaki dày dặn, thoáng, giữ form tốt.\nPhom ôm nhẹ phần cạp – tôn dáng, làm chân trông dài hơn.\nThiết kế tối giản, phù hợp nhiều phong cách.\nPhong cách gợi ýKết hợp tốt với tee, hoodie, sơ mi hoặc knitwear.\nPhù hợp cả streetwear lẫn phong cách tối giản.\nDễ dùng cho đi làm, đi học, đi chơi hằng ngày.",
    "status": "active",
    "metaTitle": "Wide Straight Jeans > Dáng suông > Beige | Whose Studio",
    "metaDescription": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông ",
    "variants": [
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BEIGE-XS",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Beige",
          "size": "XS"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BEIGE-S",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Beige",
          "size": "S"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BEIGE-M",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Beige",
          "size": "M"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BEIGE-L",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Beige",
          "size": "L"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BEIGE-XL",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Beige",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BEIGE-XXL",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Beige",
          "size": "XXL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/wide-straight-jeans-dang-suong-beige-0.jpg",
        "storageKey": "seed/products/wide-straight-jeans-dang-suong-beige-0.jpg",
        "alt": "Beige",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/wide-straight-jeans-dang-suong-beige-1.jpg",
        "storageKey": "seed/products/wide-straight-jeans-dang-suong-beige-1.jpg",
        "alt": "Beige",
        "sortOrder": 1
      }
    ]
  },
  {
    "name": "Wide Straight Jeans > Dáng suông > Beige v2",
    "slug": "wide-straight-jeans-dang-suong-beige-v2",
    "description": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông xuống ống, mang lại sự thoải mái nhưng vẫn giữ được sự gọn gàng và cân đối khi mặc.\nChất liệu jeans kaki đứng form, bền, có độ mềm vừa phải để thoải mái vận động suốt ngày dài.\nĐặc điểm nổi bậtForm Wide Straight: suông thẳng, rộng vừa, không phồng.\nChất liệu jeans kaki dày dặn, thoáng, giữ form tốt.\nPhom ôm nhẹ phần cạp – tôn dáng, làm chân trông dài hơn.\nThiết kế tối giản, phù hợp nhiều phong cách.\nPhong cách gợi ýKết hợp tốt với tee, hoodie, sơ mi hoặc knitwear.\nPhù hợp cả streetwear lẫn phong cách tối giản.\nDễ dùng cho đi làm, đi học, đi chơi hằng ngày.",
    "status": "active",
    "metaTitle": "Wide Straight Jeans > Dáng suông > Beige v2 | Whose Studio",
    "metaDescription": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông ",
    "variants": [
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--XS-BEIGE",
        "price": 280000,
        "inventory": 0,
        "options": {
          "size": "XS",
          "color": "Beige"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--S-BEIGE",
        "price": 280000,
        "inventory": 0,
        "options": {
          "size": "S",
          "color": "Beige"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--M-BEIGE",
        "price": 280000,
        "inventory": 0,
        "options": {
          "size": "M",
          "color": "Beige"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--L-BEIGE",
        "price": 280000,
        "inventory": 0,
        "options": {
          "size": "L",
          "color": "Beige"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--XL-BEIGE",
        "price": 280000,
        "inventory": 0,
        "options": {
          "size": "XL",
          "color": "Beige"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--XXL-BEIGE",
        "price": 280000,
        "inventory": 0,
        "options": {
          "size": "XXL",
          "color": "Beige"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/wide-straight-jeans-dang-suong-beige-v2-0.jpg",
        "storageKey": "seed/products/wide-straight-jeans-dang-suong-beige-v2-0.jpg",
        "alt": "Beige",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/wide-straight-jeans-dang-suong-beige-v2-1.jpg",
        "storageKey": "seed/products/wide-straight-jeans-dang-suong-beige-v2-1.jpg",
        "alt": "Beige",
        "sortOrder": 1
      }
    ]
  },
  {
    "name": "Wide Straight Jeans > Dáng suông > Black",
    "slug": "wide-straight-jeans-dang-suong-black",
    "description": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông xuống ống, mang lại sự thoải mái nhưng vẫn giữ được sự gọn gàng và cân đối khi mặc.\nChất liệu jeans kaki đứng form, bền, có độ mềm vừa phải để thoải mái vận động suốt ngày dài.\nĐặc điểm nổi bậtForm Wide Straight: suông thẳng, rộng vừa, không phồng.\nChất liệu jeans kaki dày dặn, thoáng, giữ form tốt.\nPhom ôm nhẹ phần cạp – tôn dáng, làm chân trông dài hơn.\nThiết kế tối giản, phù hợp nhiều phong cách.\nPhong cách gợi ýKết hợp tốt với tee, hoodie, sơ mi hoặc knitwear.\nPhù hợp cả streetwear lẫn phong cách tối giản.\nDễ dùng cho đi làm, đi học, đi chơi hằng ngày.",
    "status": "active",
    "metaTitle": "Wide Straight Jeans > Dáng suông > Black | Whose Studio",
    "metaDescription": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông ",
    "variants": [
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BLACK-XS",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "XS"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BLACK-S",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "S"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BLACK-M",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "M"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BLACK-L",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "L"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BLACK-XL",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--BLACK-XXL",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Black",
          "size": "XXL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/wide-straight-jeans-dang-suong-black-0.jpg",
        "storageKey": "seed/products/wide-straight-jeans-dang-suong-black-0.jpg",
        "alt": "Black",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/wide-straight-jeans-dang-suong-black-1.jpg",
        "storageKey": "seed/products/wide-straight-jeans-dang-suong-black-1.jpg",
        "alt": "Black",
        "sortOrder": 1
      }
    ]
  },
  {
    "name": "Wide Straight Jeans > Dáng suông > Brown",
    "slug": "nhan-ban-tu-wide-straight-jeans-dang-suong-stone-gray",
    "description": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông xuống ống, mang lại sự thoải mái nhưng vẫn giữ được sự gọn gàng và cân đối khi mặc.\nChất liệu jeans kaki đứng form, bền, có độ mềm vừa phải để thoải mái vận động suốt ngày dài.\nĐặc điểm nổi bậtForm Wide Straight: suông thẳng, rộng vừa, không phồng.\nChất liệu jeans kaki dày dặn, thoáng, giữ form tốt.\nPhom ôm nhẹ phần cạp – tôn dáng, làm chân trông dài hơn.\nThiết kế tối giản, phù hợp nhiều phong cách.\nPhong cách gợi ýKết hợp tốt với tee, hoodie, sơ mi hoặc knitwear.\nPhù hợp cả streetwear lẫn phong cách tối giản.\nDễ dùng cho đi làm, đi học, đi chơi hằng ngày.",
    "status": "active",
    "metaTitle": "Wide Straight Jeans > Dáng suông > Brown | Whose Studio",
    "metaDescription": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông ",
    "variants": [
      {
        "sku": "WHS-NHAN-BAN-TU-WIDE-STR-BROWN-XS",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Brown",
          "size": "XS"
        }
      },
      {
        "sku": "WHS-NHAN-BAN-TU-WIDE-STR-BROWN-S",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Brown",
          "size": "S"
        }
      },
      {
        "sku": "WHS-NHAN-BAN-TU-WIDE-STR-BROWN-M",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Brown",
          "size": "M"
        }
      },
      {
        "sku": "WHS-NHAN-BAN-TU-WIDE-STR-BROWN-L",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Brown",
          "size": "L"
        }
      },
      {
        "sku": "WHS-NHAN-BAN-TU-WIDE-STR-BROWN-XL",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Brown",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-NHAN-BAN-TU-WIDE-STR-BROWN-XXL",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Brown",
          "size": "XXL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/nhan-ban-tu-wide-straight-jeans-dang-suong-stone-gray-0.jpg",
        "storageKey": "seed/products/nhan-ban-tu-wide-straight-jeans-dang-suong-stone-gray-0.jpg",
        "alt": "Brown",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/nhan-ban-tu-wide-straight-jeans-dang-suong-stone-gray-1.jpg",
        "storageKey": "seed/products/nhan-ban-tu-wide-straight-jeans-dang-suong-stone-gray-1.jpg",
        "alt": "Brown",
        "sortOrder": 1
      }
    ]
  },
  {
    "name": "Wide Straight Jeans > Dáng suông > Dark Blue",
    "slug": "wide-straight-jeans-dang-suong-dark-blue",
    "description": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông xuống ống, mang lại sự thoải mái nhưng vẫn giữ được sự gọn gàng và cân đối khi mặc.\nChất liệu jeans kaki đứng form, bền, có độ mềm vừa phải để thoải mái vận động suốt ngày dài.\nĐặc điểm nổi bậtForm Wide Straight: suông thẳng, rộng vừa, không phồng.\nChất liệu jeans kaki dày dặn, thoáng, giữ form tốt.\nPhom ôm nhẹ phần cạp – tôn dáng, làm chân trông dài hơn.\nThiết kế tối giản, phù hợp nhiều phong cách.\nPhong cách gợi ýKết hợp tốt với tee, hoodie, sơ mi hoặc knitwear.\nPhù hợp cả streetwear lẫn phong cách tối giản.\nDễ dùng cho đi làm, đi học, đi chơi hằng ngày.",
    "status": "active",
    "metaTitle": "Wide Straight Jeans > Dáng suông > Dark Blue | Whose Studio",
    "metaDescription": "Wide Straight được thiết kế theo tinh thần tối giản, form suông thẳng – rộng vừa giúp tạo tỷ lệ đẹp và che khuyết điểm hiệu quả. Dáng quần rơi tự nhiên từ hông ",
    "variants": [
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--DARK-BLUE-XS",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Dark Blue",
          "size": "XS"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--DARK-BLUE-S",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Dark Blue",
          "size": "S"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--DARK-BLUE-M",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Dark Blue",
          "size": "M"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--DARK-BLUE-L",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Dark Blue",
          "size": "L"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--DARK-BLUE-XL",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Dark Blue",
          "size": "XL"
        }
      },
      {
        "sku": "WHS-WIDE-STRAIGHT-JEANS--DARK-BLUE-XXL",
        "price": 280000,
        "inventory": 0,
        "options": {
          "color": "Dark Blue",
          "size": "XXL"
        }
      }
    ],
    "images": [
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/wide-straight-jeans-dang-suong-dark-blue-0.jpg",
        "storageKey": "seed/products/wide-straight-jeans-dang-suong-dark-blue-0.jpg",
        "alt": "Dark Blue",
        "sortOrder": 0
      },
      {
        "url": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/wide-straight-jeans-dang-suong-dark-blue-1.jpg",
        "storageKey": "seed/products/wide-straight-jeans-dang-suong-dark-blue-1.jpg",
        "alt": "Dark Blue",
        "sortOrder": 1
      }
    ]
  }
];

export const whoseStudioCollections: SeedCollection[] = [
  {
    "name": "T-Shirts",
    "slug": "t-shirts",
    "description": "Essential tees and baby tees from Whose Studio.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-black-0.jpg",
    "productSlugs": [
      "blinkstar-tshirt-black",
      "blinkstar-tshirt-red",
      "blinkstar-tshirt-tieu-dam",
      "blinkstar-tshirt-white",
      "bodyfit-tee"
    ]
  },
  {
    "name": "Hoodies",
    "slug": "hoodies",
    "description": "Premium hoodies and zip-ups for everyday streetwear.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/507-hdz-symbol-0.jpg",
    "productSlugs": [
      "507-hdz-symbol",
      "arch-hoodie-zip",
      "arch-hoodie-zip-tieu-dam",
      "arch-hoodie-zip-tieu-nhat",
      "blank-sweater-premium-cotton-350gsm-black"
    ]
  },
  {
    "name": "Jackets",
    "slug": "jackets",
    "description": "Outerwear including nylon jackets and windbreakers.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/airframe-jacket-0.png",
    "productSlugs": [
      "airframe-jacket",
      "denim-jacket-den",
      "denim-jacket-indigo",
      "denim-jacket-kem",
      "denim-jacket-reu"
    ]
  },
  {
    "name": "Accessories",
    "slug": "accessories",
    "description": "Caps, scarves, and finishing touches.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/cap-metal-logo-whose-black-0.jpg",
    "productSlugs": [
      "cap-metal-logo-whose-black",
      "cap-metal-logo-whose-vang",
      "cap-metal-logo-whose-xanh",
      "frost-knit-scraft-270gsm-black",
      "frost-knit-scraft-270gsm-grey"
    ]
  },
  {
    "name": "Wide Straight Jeans",
    "slug": "jeans",
    "description": "Wide and straight denim fits.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/wide-straight-jeans-dang-suong-beige-0.jpg",
    "productSlugs": [
      "wide-straight-jeans-dang-suong-beige",
      "wide-straight-jeans-dang-suong-beige-v2",
      "wide-straight-jeans-dang-suong-black",
      "nhan-ban-tu-wide-straight-jeans-dang-suong-stone-gray",
      "wide-straight-jeans-dang-suong-dark-blue"
    ]
  },
  {
    "name": "Best Sellers",
    "slug": "best-sellers",
    "description": "Top picks from the Whose Studio catalog.",
    "imageUrl": "https://pub-ef48cee25c9e46b7ba7d26fd8d79918d.r2.dev/seed/products/blinkstar-tshirt-black-0.jpg",
    "productSlugs": [
      "blinkstar-tshirt-black",
      "bodyfit-tee",
      "arch-hoodie-zip",
      "airframe-jacket",
      "wide-straight-jeans-dang-suong-black"
    ]
  }
];
